<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * M2 — Scheduling (Epic-02): events, RSVPs, attendance, coach assignments and
 * their availability-conflict override log, private-event invitations, and
 * duplication records.
 *
 * Runs as the owner role (see the `migrate` make target).
 *
 * `coach_availability_override` is created here, not in Epic-01's migration,
 * even though `CoachAvailabilityConflictChecker` (Epic-01) already implements
 * the pure conflict-detection logic it logs against — see that class's own
 * docblock: "coach_availability_override is itself scheduled for Epic-02's
 * migration batch (M2), not Epic-01's (M1)". `event` and `coach_assignment`,
 * which it references, do not exist before this migration either.
 *
 * Attaches one deferred FK from M1: `child_approval_request.rsvp_id` ->
 * `rsvp(id)`, per specs/database-designer-schema.md "Migration ordering",
 * "M2 — Scheduling". Not itself deferred further — `rsvp` is created in this
 * same batch.
 *
 * RLS session variable: this migration uses `app.current_trainer`, matching
 * `App\Platform\Tenancy\TenantContext::SESSION_VARIABLE` and the two Epic-01
 * migrations — NOT `app.current_trainer_id`, which is what
 * specs/database-designer-schema.md's own "Row-Level Security" section
 * literally shows in its example SQL. That is a documentation/implementation
 * naming mismatch already present before this migration (TenantContext and
 * both M1 migrations already use the short form); this migration follows the
 * real, running code rather than the doc, since diverging would silently
 * break every policy below. Recorded in the coder's final report, not fixed
 * here — renaming a session variable Epic-01 already shipped and tested is
 * out of this epic's scope.
 *
 * @see specs/database-designer-schema.md "Scheduling module (Epic-02)"
 * @see specs/requirements-analyst-epic-02-event-management-spec.md
 */
final class Version20260810120000 extends AbstractMigration
{
    /**
     * Trainer-scoped tables created here. Every one must appear in
     * config/tenancy/trainer_scoped_tables.txt (already pre-populated).
     */
    private const TRAINER_SCOPED_TABLES = [
        'event',
        'rsvp',
        'attendance_record',
        'attendance_edit',
        'coach_assignment',
        'coach_availability_override',
        'event_invitation',
        'event_duplication_record',
    ];

    public function getDescription(): string
    {
        return 'Epic-02: events, RSVPs, attendance, coach assignments and overrides, invitations, duplication records';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform,
            'PracticePerfect targets PostgreSQL only: Row-Level Security is load-bearing.',
        );

        // --- Trainer-scoped: Scheduling -------------------------------------
        $this->addSql(<<<'SQL'
            CREATE TABLE event (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trainer_id BIGINT NOT NULL,
                title VARCHAR(100) NOT NULL,
                description TEXT DEFAULT NULL,
                event_type VARCHAR(24) NOT NULL,
                starts_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                ends_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                location VARCHAR(255) NOT NULL,
                capacity SMALLINT NOT NULL,
                visibility VARCHAR(16) DEFAULT 'public' NOT NULL,
                usd_pricing_enabled BOOLEAN DEFAULT FALSE NOT NULL,
                usd_price_minor_units INTEGER DEFAULT 0 NOT NULL,
                token_pricing_enabled BOOLEAN DEFAULT TRUE NOT NULL,
                token_price INTEGER DEFAULT 1 NOT NULL,
                min_age SMALLINT DEFAULT NULL,
                max_age SMALLINT DEFAULT NULL,
                skill_levels TEXT[] DEFAULT NULL,
                genders TEXT[] DEFAULT NULL,
                status VARCHAR(16) DEFAULT 'active' NOT NULL,
                canceled_reason TEXT DEFAULT NULL,
                canceled_by_account_id BIGINT DEFAULT NULL,
                canceled_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_event_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT fk_event_canceled_by FOREIGN KEY (canceled_by_account_id)
                    REFERENCES account (id) ON DELETE RESTRICT,
                CONSTRAINT chk_event_type CHECK (event_type IN ('training_session','private_session','small_group')),
                CONSTRAINT chk_event_dates CHECK (ends_at > starts_at),
                CONSTRAINT chk_event_capacity CHECK (capacity BETWEEN 1 AND 999),
                CONSTRAINT chk_event_visibility CHECK (visibility IN ('public','private')),
                CONSTRAINT chk_event_status CHECK (status IN ('active','canceled','completed')),
                CONSTRAINT chk_event_usd_price_nonneg CHECK (usd_price_minor_units >= 0),
                CONSTRAINT chk_event_token_price CHECK (token_price >= 1),
                -- BR-02-3: a *paid* event's amount must be > 0 — a free event
                -- just has the USD toggle off, at any (including zero) amount.
                CONSTRAINT chk_event_usd_paid_amount CHECK ((NOT usd_pricing_enabled) OR usd_price_minor_units > 0),
                CONSTRAINT chk_event_cancel_shape CHECK (
                    (status = 'canceled') = (canceled_reason IS NOT NULL AND canceled_at IS NOT NULL)
                )
            )
            SQL);
        $this->addSql('CREATE INDEX idx_event_trainer_starts ON event (trainer_id, starts_at)');
        $this->addSql('CREATE INDEX idx_event_trainer_status_starts ON event (trainer_id, status, starts_at)');
        $this->addSql('CREATE INDEX idx_event_trainer_type ON event (trainer_id, event_type)');

        $this->addSql(<<<'SQL'
            CREATE TABLE rsvp (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trainer_id BIGINT NOT NULL,
                event_id BIGINT NOT NULL,
                player_id BIGINT NOT NULL,
                status VARCHAR(24) DEFAULT 'pending_payment' NOT NULL,
                payment_method VARCHAR(8) NOT NULL,
                payment_record_id BIGINT DEFAULT NULL,
                requested_at TIMESTAMP(0) WITH TIME ZONE DEFAULT now() NOT NULL,
                confirmed_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                canceled_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                cancellation_reason TEXT DEFAULT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_rsvp_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT fk_rsvp_event FOREIGN KEY (event_id)
                    REFERENCES event (id) ON DELETE RESTRICT,
                CONSTRAINT fk_rsvp_player FOREIGN KEY (player_id)
                    REFERENCES player_profile (id) ON DELETE RESTRICT,
                CONSTRAINT chk_rsvp_status CHECK (status IN ('pending_parent_approval','pending_payment','confirmed','canceled')),
                CONSTRAINT chk_rsvp_payment_method CHECK (payment_method IN ('token','usd','free'))
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_rsvp_event_player ON rsvp (event_id, player_id)');
        $this->addSql('CREATE INDEX idx_rsvp_event_status ON rsvp (event_id, status)');
        $this->addSql('CREATE INDEX idx_rsvp_player_status ON rsvp (player_id, status)');

        $this->addSql(<<<'SQL'
            CREATE TABLE attendance_record (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trainer_id BIGINT NOT NULL,
                event_id BIGINT NOT NULL,
                player_id BIGINT NOT NULL,
                rsvp_id BIGINT NOT NULL,
                status VARCHAR(16) NOT NULL,
                recorded_by_coach_membership_id BIGINT NOT NULL,
                recorded_at TIMESTAMP(0) WITH TIME ZONE DEFAULT now() NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_attendance_record_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT fk_attendance_record_event FOREIGN KEY (event_id)
                    REFERENCES event (id) ON DELETE RESTRICT,
                CONSTRAINT fk_attendance_record_player FOREIGN KEY (player_id)
                    REFERENCES player_profile (id) ON DELETE RESTRICT,
                CONSTRAINT fk_attendance_record_rsvp FOREIGN KEY (rsvp_id)
                    REFERENCES rsvp (id) ON DELETE RESTRICT,
                CONSTRAINT fk_attendance_record_coach FOREIGN KEY (recorded_by_coach_membership_id)
                    REFERENCES coach_membership (id) ON DELETE RESTRICT,
                CONSTRAINT chk_attendance_record_status CHECK (status IN ('present','absent','late','excused'))
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_attendance_record_event_player ON attendance_record (event_id, player_id)');
        $this->addSql('CREATE INDEX idx_attendance_record_trainer_player_status ON attendance_record (trainer_id, player_id, status, recorded_at)');

        $this->addSql(<<<'SQL'
            CREATE TABLE attendance_edit (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trainer_id BIGINT NOT NULL,
                attendance_record_id BIGINT NOT NULL,
                old_status VARCHAR(16) NOT NULL,
                new_status VARCHAR(16) NOT NULL,
                edited_by_account_id BIGINT NOT NULL,
                edited_at TIMESTAMP(0) WITH TIME ZONE DEFAULT now() NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_attendance_edit_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT fk_attendance_edit_record FOREIGN KEY (attendance_record_id)
                    REFERENCES attendance_record (id) ON DELETE CASCADE,
                CONSTRAINT fk_attendance_edit_account FOREIGN KEY (edited_by_account_id)
                    REFERENCES account (id) ON DELETE RESTRICT,
                CONSTRAINT chk_attendance_edit_old_status CHECK (old_status IN ('present','absent','late','excused')),
                CONSTRAINT chk_attendance_edit_new_status CHECK (new_status IN ('present','absent','late','excused'))
            )
            SQL);
        $this->addSql('CREATE INDEX idx_attendance_edit_record ON attendance_edit (attendance_record_id, edited_at)');

        $this->addSql(<<<'SQL'
            CREATE TABLE coach_assignment (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trainer_id BIGINT NOT NULL,
                event_id BIGINT NOT NULL,
                coach_membership_id BIGINT NOT NULL,
                status VARCHAR(16) DEFAULT 'pending' NOT NULL,
                decline_reason TEXT DEFAULT NULL,
                confirmed_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                assigned_at TIMESTAMP(0) WITH TIME ZONE DEFAULT now() NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_coach_assignment_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT fk_coach_assignment_event FOREIGN KEY (event_id)
                    REFERENCES event (id) ON DELETE RESTRICT,
                CONSTRAINT fk_coach_assignment_coach FOREIGN KEY (coach_membership_id)
                    REFERENCES coach_membership (id) ON DELETE RESTRICT,
                CONSTRAINT chk_coach_assignment_status CHECK (status IN ('pending','confirmed','declined'))
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_coach_assignment_event_coach ON coach_assignment (event_id, coach_membership_id)');
        $this->addSql('CREATE INDEX idx_coach_assignment_coach_status ON coach_assignment (coach_membership_id, status)');

        $this->addSql(<<<'SQL'
            CREATE TABLE coach_availability_override (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trainer_id BIGINT NOT NULL,
                event_id BIGINT NOT NULL,
                coach_membership_id BIGINT NOT NULL,
                overridden_by_account_id BIGINT NOT NULL,
                reason TEXT NOT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT now() NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_coach_override_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT fk_coach_override_event FOREIGN KEY (event_id)
                    REFERENCES event (id) ON DELETE RESTRICT,
                CONSTRAINT fk_coach_override_coach FOREIGN KEY (coach_membership_id)
                    REFERENCES coach_membership (id) ON DELETE RESTRICT,
                CONSTRAINT fk_coach_override_account FOREIGN KEY (overridden_by_account_id)
                    REFERENCES account (id) ON DELETE RESTRICT,
                CONSTRAINT chk_coach_override_reason CHECK (char_length(reason) > 0)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_coach_override_event_coach ON coach_availability_override (event_id, coach_membership_id)');

        $this->addSql(<<<'SQL'
            CREATE TABLE event_invitation (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trainer_id BIGINT NOT NULL,
                event_id BIGINT NOT NULL,
                player_id BIGINT NOT NULL,
                invited_by_account_id BIGINT NOT NULL,
                invited_at TIMESTAMP(0) WITH TIME ZONE DEFAULT now() NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_event_invitation_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT fk_event_invitation_event FOREIGN KEY (event_id)
                    REFERENCES event (id) ON DELETE CASCADE,
                CONSTRAINT fk_event_invitation_player FOREIGN KEY (player_id)
                    REFERENCES player_profile (id) ON DELETE RESTRICT,
                CONSTRAINT fk_event_invitation_account FOREIGN KEY (invited_by_account_id)
                    REFERENCES account (id) ON DELETE RESTRICT
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_event_invitation_event_player ON event_invitation (event_id, player_id)');
        $this->addSql('CREATE INDEX idx_event_invitation_player ON event_invitation (player_id)');

        $this->addSql(<<<'SQL'
            CREATE TABLE event_duplication_record (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trainer_id BIGINT NOT NULL,
                original_event_id BIGINT NOT NULL,
                new_event_id BIGINT NOT NULL,
                duplicated_by_account_id BIGINT NOT NULL,
                duplicated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT now() NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_event_duplication_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT fk_event_duplication_original FOREIGN KEY (original_event_id)
                    REFERENCES event (id) ON DELETE RESTRICT,
                CONSTRAINT fk_event_duplication_new FOREIGN KEY (new_event_id)
                    REFERENCES event (id) ON DELETE RESTRICT,
                CONSTRAINT fk_event_duplication_account FOREIGN KEY (duplicated_by_account_id)
                    REFERENCES account (id) ON DELETE RESTRICT
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_event_duplication_new_event ON event_duplication_record (new_event_id)');
        $this->addSql('CREATE INDEX idx_event_duplication_original ON event_duplication_record (original_event_id)');

        // --- Deferred FK from M1: child_approval_request.rsvp_id -----------
        $this->addSql(<<<'SQL'
            ALTER TABLE child_approval_request
                ADD CONSTRAINT fk_car_rsvp FOREIGN KEY (rsvp_id)
                    REFERENCES rsvp (id) ON DELETE CASCADE
            SQL);

        $this->applyRowLevelSecurity();
    }

    /**
     * Tenancy layer 5. Identical shape to the Epic-01 migrations' — see
     * Version20260809140000 for the reasoning behind USING + WITH CHECK.
     */
    private function applyRowLevelSecurity(): void
    {
        foreach (self::TRAINER_SCOPED_TABLES as $table) {
            $this->addSql(sprintf('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', $table));

            $this->addSql(sprintf(
                <<<'SQL'
                    CREATE POLICY %1$s_tenant_isolation ON %1$s
                        USING (trainer_id = NULLIF(current_setting('app.current_trainer', true), '')::bigint)
                        WITH CHECK (trainer_id = NULLIF(current_setting('app.current_trainer', true), '')::bigint)
                    SQL,
                $table,
            ));
        }
    }

    public function down(Schema $schema): void
    {
        foreach (self::TRAINER_SCOPED_TABLES as $table) {
            $this->addSql(sprintf('DROP POLICY IF EXISTS %1$s_tenant_isolation ON %1$s', $table));
        }

        $this->addSql('ALTER TABLE child_approval_request DROP CONSTRAINT IF EXISTS fk_car_rsvp');

        $this->addSql('DROP TABLE IF EXISTS event_duplication_record');
        $this->addSql('DROP TABLE IF EXISTS event_invitation');
        $this->addSql('DROP TABLE IF EXISTS coach_availability_override');
        $this->addSql('DROP TABLE IF EXISTS coach_assignment');
        $this->addSql('DROP TABLE IF EXISTS attendance_edit');
        $this->addSql('DROP TABLE IF EXISTS attendance_record');
        $this->addSql('DROP TABLE IF EXISTS rsvp');
        $this->addSql('DROP TABLE IF EXISTS event');
    }
}
