<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * M7 — Forms (Epic-08): camp/evaluation forms and their public submissions.
 * The last migration in the platform's build order (A10: 01 -> 02 ->
 * {03, 04} -> 05 -> {06, 07, 08}).
 *
 * Runs as the owner role (see the `migrate` make target). The application
 * role holds no DDL, which is what keeps Row-Level Security meaningful.
 *
 * **Two deviations from specs/database-designer-schema.md's literal text**,
 * both forced rather than chosen, recorded here and in the coder's final
 * report — matching the precedent Version20260811100000 and its own
 * predecessors already established for this kind of conflict:
 *
 * 1. **`form_submission` gains an `attended BOOLEAN NOT NULL DEFAULT
 *    false` column beyond the schema doc's own listed columns.** AC-08-20
 *    ("Trainer marks attendance per participant via checkboxes") names a
 *    concrete, testable requirement with nowhere on the settled schema to
 *    persist it. Matches the precedent `stripe_event_receipt.raw_payload`
 *    already set in Version20260811100000: an addition forced by a
 *    requirement the schema text omitted, not a silent one. A plain
 *    boolean, not a richer state machine — the AC says "checkboxes."
 * 2. **`fk_payment_record_form_submission` and
 *    `fk_form_submission_payment_record` are both `ON DELETE NO ACTION
 *    DEFERRABLE INITIALLY DEFERRED`**, matching exactly the treatment
 *    Version20260811100000 already gives `rsvp`/`payment_record`'s own
 *    mutual reference, and for the identical reason: `form_submission.
 *    payment_record_id` and `payment_record.related_form_submission_id`
 *    point at each other, and two tables whose foreign keys point at each
 *    other have no valid linear deletion order under Postgres's default
 *    (immediate, per-statement) constraint checking — `doctrine:
 *    fixtures:load`'s `ORMPurger`, which `make test`/`make seed` both
 *    depend on, fails with `SQLSTATE[23503]` in this exact shape once
 *    `PaymentRecord::$relatedFormSubmission` and `FormSubmission::
 *    $paymentRecord` are both real ORM relations (required so `ORMPurger`
 *    can compute deletion order at all — see `PaymentRecord::
 *    $relatedFormSubmission`'s own docblock, which restates why a scalar
 *    column carrying a real, unmapped FK is invisible to it). Every other
 *    FK in this migration keeps `RESTRICT`.
 *
 * `payment_record.related_form_submission_id`'s CHECK shape
 * (`chk_payment_record_related_shape`) already accounts for
 * `camp_registration` — Version20260811100000 wrote it forward-compatible
 * before this epic existed, so it needs no change here.
 *
 * RLS session variable: `app.current_trainer`, matching
 * `App\Platform\Tenancy\TenantContext::SESSION_VARIABLE` and every prior
 * migration.
 *
 * @see specs/database-designer-schema.md "Forms module (Epic-08)"
 * @see specs/architect-architecture.md "Module map" — Forms
 * @see specs/requirements-analyst-epic-08-forms-registration-spec.md
 */
final class Version20260811150000 extends AbstractMigration
{
    private const STANDARD_TRAINER_SCOPED_TABLES = ['form', 'form_submission'];

    public function getDescription(): string
    {
        return 'Epic-08: form, form_submission + payment_record.related_form_submission_id FK (both directions, DEFERRABLE — see docblock).';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform,
            'PracticePerfect targets PostgreSQL only: Row-Level Security is load-bearing.',
        );

        // --- form -----------------------------------------------------------
        $this->addSql(<<<'SQL'
            CREATE TABLE form (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trainer_id BIGINT NOT NULL,
                form_type VARCHAR(16) NOT NULL,
                name VARCHAR(255) NOT NULL,
                description TEXT DEFAULT NULL,
                price_minor_units INTEGER DEFAULT NULL,
                capacity_limit INTEGER DEFAULT NULL,
                is_active BOOLEAN DEFAULT true NOT NULL,
                field_definitions JSONB DEFAULT '[]' NOT NULL,
                shareable_slug VARCHAR(64) NOT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_form_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT uniq_form_shareable_slug UNIQUE (shareable_slug),
                CONSTRAINT chk_form_type CHECK (form_type IN ('camp', 'evaluation')),
                CONSTRAINT chk_form_price CHECK (price_minor_units IS NULL OR price_minor_units >= 0),
                CONSTRAINT chk_form_capacity CHECK (
                    capacity_limit IS NULL OR (form_type = 'camp' AND capacity_limit BETWEEN 1 AND 1000)
                ),
                CONSTRAINT chk_form_name CHECK (char_length(trim(name)) > 0)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_form_trainer_type ON form (trainer_id, form_type)');

        // --- form_submission --------------------------------------------------
        // payment_record_id -> payment_record(id) is declared directly here:
        // payment_record already exists (Epic-05, M4). DEFERRABLE both
        // directions — see this migration's own docblock, point 2.
        $this->addSql(<<<'SQL'
            CREATE TABLE form_submission (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trainer_id BIGINT NOT NULL,
                form_id BIGINT NOT NULL,
                submission_data JSONB NOT NULL,
                contact_email CITEXT NOT NULL,
                payment_status VARCHAR(16) DEFAULT 'free' NOT NULL,
                payment_record_id BIGINT DEFAULT NULL,
                submitted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT now() NOT NULL,
                converted_account_id BIGINT DEFAULT NULL,
                converted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                attended BOOLEAN DEFAULT false NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_form_submission_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT fk_form_submission_form FOREIGN KEY (form_id)
                    REFERENCES form (id) ON DELETE RESTRICT,
                CONSTRAINT fk_form_submission_payment_record FOREIGN KEY (payment_record_id)
                    REFERENCES payment_record (id) ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
                CONSTRAINT fk_form_submission_converted_account FOREIGN KEY (converted_account_id)
                    REFERENCES account (id) ON DELETE RESTRICT,
                CONSTRAINT uniq_form_submission_form_email UNIQUE (form_id, contact_email),
                CONSTRAINT chk_form_submission_payment_status CHECK (payment_status IN ('free', 'paid', 'pending')),
                CONSTRAINT chk_form_submission_converted_shape CHECK (
                    (converted_account_id IS NULL) = (converted_at IS NULL)
                )
            )
            SQL);
        $this->addSql('CREATE INDEX idx_form_submission_trainer_form_status ON form_submission (trainer_id, form_id, payment_status)');
        $this->addSql('CREATE INDEX idx_form_submission_form_converted ON form_submission (form_id, converted_account_id)');

        // --- Deferred FK from M4, now that form_submission exists -----------
        // See this migration's own docblock, point 2, for why NO ACTION
        // DEFERRABLE INITIALLY DEFERRED, not RESTRICT.
        $this->addSql(<<<'SQL'
            ALTER TABLE payment_record
                ADD CONSTRAINT fk_payment_record_form_submission FOREIGN KEY (related_form_submission_id)
                    REFERENCES form_submission (id) ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED
            SQL);
        $this->addSql('CREATE INDEX idx_payment_record_related_form_submission ON payment_record (related_form_submission_id) WHERE related_form_submission_id IS NOT NULL');

        $this->applyRowLevelSecurity();
    }

    private function applyRowLevelSecurity(): void
    {
        foreach (self::STANDARD_TRAINER_SCOPED_TABLES as $table) {
            $this->addSql(sprintf('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', $table));

            $this->addSql(sprintf(
                <<<'SQL'
                    CREATE POLICY %1$s_tenant_isolation ON %1$s
                        USING (trainer_id = NULLIF(current_setting('app.current_trainer', true), '')::bigint)
                        WITH CHECK (trainer_id = NULLIF(current_setting('app.current_trainer', true), '')::bigint)
                    SQL,
                $table,
            ));
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE payment_record DROP CONSTRAINT IF EXISTS fk_payment_record_form_submission');

        foreach (self::STANDARD_TRAINER_SCOPED_TABLES as $table) {
            $this->addSql(sprintf('DROP POLICY IF EXISTS %1$s_tenant_isolation ON %1$s', $table));
        }

        $this->addSql('DROP TABLE IF EXISTS form_submission');
        $this->addSql('DROP TABLE IF EXISTS form');
    }
}
