<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * M5 — Growth (Epic-06): referral links, referrals, per-player assist
 * counts, coupons, and coupon redemptions.
 *
 * RLS session variable: `app.current_trainer`, matching every migration
 * since Epic-01 (`App\Platform\Tenancy\TenantContext::SESSION_VARIABLE`).
 *
 * **No `rewarded` status on `referral`** despite the epic's own Data
 * Requirements listing Pending/Converted/Rewarded — whether a reward was
 * actually granted is a fact about the token ledger (a `token_entry` of
 * kind `referral_reward` referencing this table), not a fact about this
 * row; see `Referral`'s own docblock and
 * `specs/database-designer-schema.md` "`referral`".
 *
 * **Deferred FK now attached**: `token_entry.referral_id` was created as a
 * deferred, unconstrained column in Version20260811100000 ("Growth/M5 does
 * not exist yet"). Both sides now exist, so the real FK is added here —
 * same "attach the deferred FK once both sides exist" idiom that migration
 * already used for `rsvp.payment_record_id` and
 * `playlist_access_grant.payment_record_id`.
 *
 * Runs as the owner role (see the `migrate` make target).
 *
 * @see specs/database-designer-schema.md "Growth module (Epic-06)"
 * @see specs/requirements-analyst-epic-06-marketing-growth-spec.md
 */
final class Version20260811130000 extends AbstractMigration
{
    /**
     * Trainer-scoped tables created here. Every one must appear in
     * config/tenancy/trainer_scoped_tables.txt (already pre-populated).
     */
    private const TRAINER_SCOPED_TABLES = [
        'referral_link',
        'referral',
        'referral_assist_count',
        'coupon',
        'coupon_redemption',
    ];

    public function getDescription(): string
    {
        return 'Epic-06: referral_link, referral, referral_assist_count, coupon, coupon_redemption + token_entry.referral_id FK.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform,
            'PracticePerfect targets PostgreSQL only: Row-Level Security is load-bearing.',
        );

        // --- referral_link ----------------------------------------------------
        // AC-06-1: one per (player, trainer), no separate code column — the
        // URL is composed from trainer.slug + this row's player id at
        // render time (see ReferralLink's own docblock).
        $this->addSql(<<<'SQL'
            CREATE TABLE referral_link (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trainer_id BIGINT NOT NULL,
                player_id BIGINT NOT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT now() NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_referral_link_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT fk_referral_link_player FOREIGN KEY (player_id)
                    REFERENCES player_profile (id) ON DELETE RESTRICT
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_referral_link_trainer_player ON referral_link (trainer_id, player_id)');

        // --- referral -----------------------------------------------------
        $this->addSql(<<<'SQL'
            CREATE TABLE referral (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trainer_id BIGINT NOT NULL,
                referral_link_id BIGINT NOT NULL,
                referrer_player_id BIGINT NOT NULL,
                referee_player_id BIGINT NOT NULL,
                clicked_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                registered_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                status VARCHAR(16) DEFAULT 'pending' NOT NULL,
                first_purchase_payment_record_id BIGINT DEFAULT NULL,
                first_purchase_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_referral_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT fk_referral_link FOREIGN KEY (referral_link_id)
                    REFERENCES referral_link (id) ON DELETE RESTRICT,
                CONSTRAINT fk_referral_referrer FOREIGN KEY (referrer_player_id)
                    REFERENCES player_profile (id) ON DELETE RESTRICT,
                CONSTRAINT fk_referral_referee FOREIGN KEY (referee_player_id)
                    REFERENCES player_profile (id) ON DELETE RESTRICT,
                CONSTRAINT fk_referral_payment_record FOREIGN KEY (first_purchase_payment_record_id)
                    REFERENCES payment_record (id) ON DELETE RESTRICT,
                CONSTRAINT chk_referral_status CHECK (status IN ('pending', 'converted')),
                CONSTRAINT chk_referral_converted_shape CHECK (
                    (status = 'converted') = (first_purchase_payment_record_id IS NOT NULL AND first_purchase_at IS NOT NULL)
                ),
                CONSTRAINT chk_referral_no_self_referral CHECK (referrer_player_id <> referee_player_id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_referral_referee ON referral (referee_player_id)');
        $this->addSql('CREATE INDEX idx_referral_referrer_trainer ON referral (referrer_player_id, trainer_id)');
        $this->addSql("CREATE INDEX idx_referral_pending ON referral (status) WHERE status = 'pending'");

        // --- referral_assist_count ------------------------------------------
        $this->addSql(<<<'SQL'
            CREATE TABLE referral_assist_count (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trainer_id BIGINT NOT NULL,
                player_id BIGINT NOT NULL,
                assist_count INTEGER DEFAULT 0 NOT NULL,
                updated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT now() NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_referral_assist_count_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT fk_referral_assist_count_player FOREIGN KEY (player_id)
                    REFERENCES player_profile (id) ON DELETE RESTRICT,
                CONSTRAINT chk_referral_assist_count_nonnegative CHECK (assist_count >= 0)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_referral_assist_count_trainer_player ON referral_assist_count (trainer_id, player_id)');

        // --- coupon ---------------------------------------------------------
        $this->addSql(<<<'SQL'
            CREATE TABLE coupon (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trainer_id BIGINT NOT NULL,
                code VARCHAR(50) NOT NULL,
                discount_type VARCHAR(16) NOT NULL,
                discount_value INTEGER NOT NULL,
                applies_to VARCHAR(16) NOT NULL,
                usage_limit INTEGER DEFAULT NULL,
                usage_count INTEGER DEFAULT 0 NOT NULL,
                eligibility VARCHAR(24) DEFAULT 'any_player' NOT NULL,
                expires_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                is_active BOOLEAN DEFAULT true NOT NULL,
                created_by_account_id BIGINT NOT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE DEFAULT now() NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_coupon_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT fk_coupon_created_by FOREIGN KEY (created_by_account_id)
                    REFERENCES account (id) ON DELETE RESTRICT,
                CONSTRAINT chk_coupon_discount_type CHECK (discount_type IN ('percentage', 'fixed')),
                CONSTRAINT chk_coupon_discount_value CHECK (
                    (discount_type = 'percentage' AND discount_value BETWEEN 1 AND 100)
                    OR (discount_type = 'fixed' AND discount_value > 0)
                ),
                CONSTRAINT chk_coupon_applies_to CHECK (applies_to IN ('events', 'content', 'both')),
                CONSTRAINT chk_coupon_eligibility CHECK (eligibility IN ('any_player', 'new_players_only')),
                CONSTRAINT chk_coupon_usage_limit CHECK (usage_limit IS NULL OR usage_count <= usage_limit)
            )
            SQL);
        // BR-06-11: scoped per trainer, not global — coupon codes are
        // case-sensitive (plain VARCHAR equality; see Coupon's own docblock).
        $this->addSql('CREATE UNIQUE INDEX uniq_coupon_trainer_code ON coupon (trainer_id, code)');
        $this->addSql('CREATE INDEX idx_coupon_trainer_code_active ON coupon (trainer_id, code) WHERE is_active');

        // --- coupon_redemption -----------------------------------------------
        $this->addSql(<<<'SQL'
            CREATE TABLE coupon_redemption (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trainer_id BIGINT NOT NULL,
                coupon_id BIGINT NOT NULL,
                player_id BIGINT NOT NULL,
                payment_record_id BIGINT NOT NULL,
                original_price_minor_units INTEGER NOT NULL,
                discount_amount_minor_units INTEGER NOT NULL,
                final_price_minor_units INTEGER NOT NULL,
                redeemed_at TIMESTAMP(0) WITH TIME ZONE DEFAULT now() NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_coupon_redemption_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT fk_coupon_redemption_coupon FOREIGN KEY (coupon_id)
                    REFERENCES coupon (id) ON DELETE RESTRICT,
                CONSTRAINT fk_coupon_redemption_player FOREIGN KEY (player_id)
                    REFERENCES player_profile (id) ON DELETE RESTRICT,
                CONSTRAINT fk_coupon_redemption_payment_record FOREIGN KEY (payment_record_id)
                    REFERENCES payment_record (id) ON DELETE RESTRICT,
                CONSTRAINT chk_coupon_redemption_discount_nonnegative CHECK (discount_amount_minor_units >= 0),
                CONSTRAINT chk_coupon_redemption_final_price CHECK (final_price_minor_units = original_price_minor_units - discount_amount_minor_units),
                CONSTRAINT chk_coupon_redemption_final_price_nonnegative CHECK (final_price_minor_units >= 0)
            )
            SQL);
        // BR-06-10: only one coupon per transaction, enforced structurally —
        // a payment can fund at most one redemption row.
        $this->addSql('CREATE UNIQUE INDEX uniq_coupon_redemption_payment_record ON coupon_redemption (payment_record_id)');
        $this->addSql('CREATE INDEX idx_coupon_redemption_coupon ON coupon_redemption (coupon_id)');

        // --- deferred FK now attached (see this migration's own docblock) ---
        $this->addSql(<<<'SQL'
            ALTER TABLE token_entry
                ADD CONSTRAINT fk_token_entry_referral FOREIGN KEY (referral_id)
                    REFERENCES referral (id) ON DELETE RESTRICT
            SQL);

        $this->applyRowLevelSecurity();
    }

    /**
     * Tenancy layer 5. Identical shape to every migration since Epic-01 —
     * see Version20260810120000 for the reasoning behind USING + WITH CHECK.
     */
    private function applyRowLevelSecurity(): void
    {
        foreach (self::TRAINER_SCOPED_TABLES as $table) {
            $this->addSql(sprintf('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', $table));

            $this->addSql(sprintf(
                <<<'SQL'
                    CREATE POLICY %1$s_tenant_isolation ON %1$s
                        USING (trainer_id = NULLIF(current_setting('app.current_trainer', true), '')::bigint)
                        WITH CHECK (trainer_id = NULLIF(current_setting('app.current_trainer', true), '')::bigint)
                    SQL,
                $table,
            ));
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE token_entry DROP CONSTRAINT IF EXISTS fk_token_entry_referral');

        foreach (self::TRAINER_SCOPED_TABLES as $table) {
            $this->addSql(sprintf('DROP POLICY IF EXISTS %1$s_tenant_isolation ON %1$s', $table));
        }

        $this->addSql('DROP TABLE IF EXISTS coupon_redemption');
        $this->addSql('DROP TABLE IF EXISTS coupon');
        $this->addSql('DROP TABLE IF EXISTS referral_assist_count');
        $this->addSql('DROP TABLE IF EXISTS referral');
        $this->addSql('DROP TABLE IF EXISTS referral_link');
    }
}
