<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Epic-01, continued: everything the first M1 migration deferred —
 * parent/child links, tokens, GDPR deletion records, branding, the audit log,
 * impersonation, ShareLinks and their open-log, coach memberships,
 * availability windows, and child approval requests. Completes the "Identity
 * + Platform core" batch started by Version20260809140000.
 *
 * Runs as the owner role (see the `migrate` make target).
 *
 * Deviations from specs/database-designer-schema.md, recorded rather than
 * silently applied — both relax a CHECK constraint that would otherwise
 * demand a value from a table that does not exist until a later epic:
 *
 * - `player_trainer_membership.share_link_id` carries no
 *   `(source = 'sharelink') = (share_link_id IS NOT NULL)` CHECK. The column
 *   exists (BR-01-27) and is populated whenever a real ShareLink is known,
 *   but the equality is not enforced as an invariant.
 * - `child_approval_request` keeps its `action_type` CHECK but not the
 *   "exactly one of rsvp_id / requested_token_package_id /
 *   requested_playlist_id is populated, matching action_type" CHECK — those
 *   three columns are deliberately FK-less deferred columns (per the
 *   schema's own "Deferred FK attachment" convention) because `rsvp`,
 *   `token_package` and `playlist` do not exist until Epic-02/04/05, so
 *   Epic-01 has no real id to ever put in two of the three slots.
 *
 * @see specs/database-designer-schema.md
 * @see specs/requirements-analyst-epic-01-user-management-spec.md
 */
final class Version20260810090000 extends AbstractMigration
{
    /**
     * Trainer-scoped tables created here. Every one must appear in
     * config/tenancy/trainer_scoped_tables.txt (already pre-populated).
     */
    private const TRAINER_SCOPED_TABLES = [
        'share_link',
        'share_link_open',
        'coach_membership',
        'availability_window',
        'child_approval_request',
    ];

    public function getDescription(): string
    {
        return 'Epic-01: parent/child links, tokens, GDPR record, branding, audit log, impersonation, ShareLinks, coach memberships, availability, child approvals';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform,
            'PracticePerfect targets PostgreSQL only: Row-Level Security is load-bearing.',
        );

        // --- trainer: organization detail columns (AC-01-51) not yet created
        $this->addSql('ALTER TABLE trainer ADD COLUMN organization_address VARCHAR(500) DEFAULT NULL');
        $this->addSql('ALTER TABLE trainer ADD COLUMN organization_website VARCHAR(2048) DEFAULT NULL');
        $this->addSql('ALTER TABLE trainer ADD COLUMN organization_description TEXT DEFAULT NULL');

        // --- player_profile: columns named by the schema but not yet created
        // (AC-01-16, AC-01-51: school/jersey/emergency-contact/photo).
        $this->addSql('ALTER TABLE player_profile ADD COLUMN school_or_team VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE player_profile ADD COLUMN jersey_number VARCHAR(16) DEFAULT NULL');
        $this->addSql('ALTER TABLE player_profile ADD COLUMN emergency_contact_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE player_profile ADD COLUMN emergency_contact_phone VARCHAR(32) DEFAULT NULL');
        $this->addSql('ALTER TABLE player_profile ADD COLUMN photo_url VARCHAR(2048) DEFAULT NULL');

        // --- Global: identity ---------------------------------------------
        $this->addSql(<<<'SQL'
            CREATE TABLE parent_child_link (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                parent_account_id BIGINT NOT NULL,
                child_player_id BIGINT NOT NULL,
                child_account_id BIGINT DEFAULT NULL,
                allow_token_spending_without_approval BOOLEAN DEFAULT FALSE NOT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_pcl_parent FOREIGN KEY (parent_account_id)
                    REFERENCES account (id) ON DELETE RESTRICT,
                CONSTRAINT fk_pcl_child_player FOREIGN KEY (child_player_id)
                    REFERENCES player_profile (id) ON DELETE RESTRICT,
                CONSTRAINT fk_pcl_child_account FOREIGN KEY (child_account_id)
                    REFERENCES account (id) ON DELETE RESTRICT,
                CONSTRAINT chk_pcl_parent_not_child CHECK (parent_account_id <> child_account_id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_pcl_child_player ON parent_child_link (child_player_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_pcl_child_account ON parent_child_link (child_account_id)');
        $this->addSql('CREATE INDEX idx_pcl_parent ON parent_child_link (parent_account_id)');

        $this->addSql(<<<'SQL'
            CREATE TABLE email_verification_token (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                account_id BIGINT NOT NULL,
                token_hash VARCHAR(255) NOT NULL,
                expires_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                consumed_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_evt_account FOREIGN KEY (account_id)
                    REFERENCES account (id) ON DELETE CASCADE
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_evt_token_hash ON email_verification_token (token_hash)');
        $this->addSql('CREATE INDEX idx_evt_account ON email_verification_token (account_id)');

        $this->addSql(<<<'SQL'
            CREATE TABLE password_reset_token (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                account_id BIGINT NOT NULL,
                token_hash VARCHAR(255) NOT NULL,
                expires_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                consumed_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_prt_account FOREIGN KEY (account_id)
                    REFERENCES account (id) ON DELETE CASCADE
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_prt_token_hash ON password_reset_token (token_hash)');
        $this->addSql('CREATE INDEX idx_prt_account ON password_reset_token (account_id)');

        $this->addSql(<<<'SQL'
            CREATE TABLE user_deletion_record (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                original_account_id BIGINT NOT NULL,
                original_email VARCHAR(255) NOT NULL,
                deleted_by_account_id BIGINT NOT NULL,
                reason TEXT DEFAULT NULL,
                deleted_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_udr_original_account FOREIGN KEY (original_account_id)
                    REFERENCES account (id) ON DELETE RESTRICT,
                CONSTRAINT fk_udr_deleted_by FOREIGN KEY (deleted_by_account_id)
                    REFERENCES account (id) ON DELETE RESTRICT
            )
            SQL);
        $this->addSql('CREATE INDEX idx_udr_original_account ON user_deletion_record (original_account_id)');

        // --- Global: platform ------------------------------------------------
        $this->addSql(<<<'SQL'
            CREATE TABLE trainer_branding_settings (
                trainer_id BIGINT NOT NULL,
                logo_path VARCHAR(2048) DEFAULT NULL,
                primary_color_hex CHAR(7) DEFAULT NULL,
                updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY(trainer_id),
                CONSTRAINT fk_tbs_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE CASCADE,
                CONSTRAINT chk_tbs_color CHECK (primary_color_hex IS NULL OR primary_color_hex ~ '^#[0-9A-Fa-f]{6}$')
            )
            SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE audit_log_entry (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                occurred_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                actor_account_id BIGINT DEFAULT NULL,
                action_type VARCHAR(64) NOT NULL,
                subject_type VARCHAR(64) NOT NULL,
                subject_id BIGINT DEFAULT NULL,
                related_trainer_id BIGINT DEFAULT NULL,
                details JSONB DEFAULT '{}' NOT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_audit_actor FOREIGN KEY (actor_account_id)
                    REFERENCES account (id) ON DELETE RESTRICT,
                CONSTRAINT fk_audit_trainer FOREIGN KEY (related_trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT chk_audit_action_type CHECK (char_length(action_type) > 0)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_audit_occurred_at ON audit_log_entry (occurred_at)');
        $this->addSql('CREATE INDEX idx_audit_trainer_occurred_at ON audit_log_entry (related_trainer_id, occurred_at) WHERE related_trainer_id IS NOT NULL');
        $this->addSql('CREATE INDEX idx_audit_action_type ON audit_log_entry (action_type)');
        $this->addSql('CREATE INDEX idx_audit_actor ON audit_log_entry (actor_account_id)');
        // I7 / BR-07-6: append-only is a database privilege, not a code
        // convention. pp_app keeps INSERT + SELECT only.
        $this->addSql('REVOKE UPDATE, DELETE ON audit_log_entry FROM pp_app');

        $this->addSql(<<<'SQL'
            CREATE TABLE impersonation_session (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                admin_account_id BIGINT NOT NULL,
                target_account_id BIGINT NOT NULL,
                started_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                ended_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                ended_reason VARCHAR(16) DEFAULT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_impersonation_admin FOREIGN KEY (admin_account_id)
                    REFERENCES account (id) ON DELETE RESTRICT,
                CONSTRAINT fk_impersonation_target FOREIGN KEY (target_account_id)
                    REFERENCES account (id) ON DELETE RESTRICT,
                CONSTRAINT chk_impersonation_not_self CHECK (admin_account_id <> target_account_id),
                CONSTRAINT chk_impersonation_reason CHECK (ended_reason IS NULL OR ended_reason IN ('manual','expired'))
            )
            SQL);
        $this->addSql('CREATE INDEX idx_impersonation_target ON impersonation_session (target_account_id)');
        $this->addSql('CREATE INDEX idx_impersonation_admin_open ON impersonation_session (admin_account_id) WHERE ended_at IS NULL');

        // --- Trainer-scoped: identity ----------------------------------------
        $this->addSql(<<<'SQL'
            CREATE TABLE share_link (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trainer_id BIGINT NOT NULL,
                code VARCHAR(64) NOT NULL,
                link_type VARCHAR(16) NOT NULL,
                created_by_account_id BIGINT NOT NULL,
                target_email CITEXT DEFAULT NULL,
                expires_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                max_uses INTEGER DEFAULT NULL,
                use_count INTEGER DEFAULT 0 NOT NULL,
                is_active BOOLEAN DEFAULT TRUE NOT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_share_link_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT fk_share_link_created_by FOREIGN KEY (created_by_account_id)
                    REFERENCES account (id) ON DELETE RESTRICT,
                CONSTRAINT chk_share_link_type CHECK (link_type IN ('static_player','unique_coach')),
                CONSTRAINT chk_share_link_coach_shape CHECK (
                    (link_type <> 'unique_coach')
                    OR (target_email IS NOT NULL AND expires_at IS NOT NULL AND max_uses = 1)
                ),
                CONSTRAINT chk_share_link_static_shape CHECK (
                    (link_type <> 'static_player')
                    OR (max_uses IS NULL AND expires_at IS NULL)
                )
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_share_link_code ON share_link (code)');
        $this->addSql('CREATE INDEX idx_share_link_trainer ON share_link (trainer_id)');
        $this->addSql("CREATE INDEX idx_share_link_coach_expiry ON share_link (expires_at) WHERE link_type = 'unique_coach' AND is_active");

        $this->addSql(<<<'SQL'
            CREATE TABLE share_link_open (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trainer_id BIGINT NOT NULL,
                share_link_id BIGINT NOT NULL,
                opened_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                ip_address VARCHAR(45) DEFAULT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_slo_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT fk_slo_share_link FOREIGN KEY (share_link_id)
                    REFERENCES share_link (id) ON DELETE CASCADE
            )
            SQL);
        $this->addSql('CREATE INDEX idx_share_link_open_link ON share_link_open (share_link_id, opened_at)');

        $this->addSql(<<<'SQL'
            CREATE TABLE coach_membership (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trainer_id BIGINT NOT NULL,
                account_id BIGINT NOT NULL,
                status VARCHAR(16) DEFAULT 'pending' NOT NULL,
                bio TEXT DEFAULT NULL,
                credentials TEXT DEFAULT NULL,
                certifications TEXT DEFAULT NULL,
                is_public_profile BOOLEAN DEFAULT FALSE NOT NULL,
                invited_via_share_link_id BIGINT DEFAULT NULL,
                joined_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_coach_membership_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT fk_coach_membership_account FOREIGN KEY (account_id)
                    REFERENCES account (id) ON DELETE RESTRICT,
                CONSTRAINT fk_coach_membership_share_link FOREIGN KEY (invited_via_share_link_id)
                    REFERENCES share_link (id) ON DELETE RESTRICT,
                CONSTRAINT chk_coach_membership_status CHECK (status IN ('pending','active','declined'))
            )
            SQL);
        $this->addSql('CREATE INDEX idx_coach_membership_trainer_status ON coach_membership (trainer_id, status)');
        $this->addSql('CREATE INDEX idx_coach_membership_account ON coach_membership (account_id)');
        // BR-01-11: a coach cannot be active under more than one trainer at
        // once. No trainer_id in this key on purpose — see the entity's
        // docblock for why a unique index reaches across RLS-hidden rows and
        // why that is deliberate here, not a leak.
        $this->addSql("CREATE UNIQUE INDEX uniq_coach_membership_active_account ON coach_membership (account_id) WHERE status = 'active'");

        $this->addSql(<<<'SQL'
            CREATE TABLE availability_window (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trainer_id BIGINT NOT NULL,
                owner_type VARCHAR(16) NOT NULL,
                coach_membership_id BIGINT DEFAULT NULL,
                player_id BIGINT DEFAULT NULL,
                day_of_week SMALLINT NOT NULL,
                start_time TIME(0) WITHOUT TIME ZONE NOT NULL,
                end_time TIME(0) WITHOUT TIME ZONE NOT NULL,
                is_available BOOLEAN DEFAULT TRUE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_availability_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT fk_availability_coach FOREIGN KEY (coach_membership_id)
                    REFERENCES coach_membership (id) ON DELETE CASCADE,
                CONSTRAINT fk_availability_player FOREIGN KEY (player_id)
                    REFERENCES player_profile (id) ON DELETE CASCADE,
                CONSTRAINT chk_availability_owner_type CHECK (owner_type IN ('coach','player')),
                CONSTRAINT chk_availability_owner_coach CHECK ((owner_type <> 'coach') OR (coach_membership_id IS NOT NULL)),
                CONSTRAINT chk_availability_owner_player CHECK ((owner_type <> 'player') OR (player_id IS NOT NULL)),
                CONSTRAINT chk_availability_day CHECK (day_of_week BETWEEN 0 AND 6),
                CONSTRAINT chk_availability_range CHECK (end_time > start_time)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_availability_coach_day ON availability_window (coach_membership_id, day_of_week)');
        $this->addSql('CREATE INDEX idx_availability_player_day ON availability_window (player_id, day_of_week)');

        $this->addSql(<<<'SQL'
            CREATE TABLE child_approval_request (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trainer_id BIGINT NOT NULL,
                child_player_id BIGINT NOT NULL,
                parent_account_id BIGINT NOT NULL,
                action_type VARCHAR(20) NOT NULL,
                rsvp_id BIGINT DEFAULT NULL,
                requested_token_package_id BIGINT DEFAULT NULL,
                requested_playlist_id BIGINT DEFAULT NULL,
                status VARCHAR(16) DEFAULT 'pending' NOT NULL,
                requested_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                responded_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                parent_note TEXT DEFAULT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_car_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT fk_car_child FOREIGN KEY (child_player_id)
                    REFERENCES player_profile (id) ON DELETE RESTRICT,
                CONSTRAINT fk_car_parent FOREIGN KEY (parent_account_id)
                    REFERENCES account (id) ON DELETE RESTRICT,
                CONSTRAINT chk_car_action_type CHECK (action_type IN ('rsvp','token_purchase','content_purchase')),
                CONSTRAINT chk_car_status CHECK (status IN ('pending','approved','denied'))
            )
            SQL);
        $this->addSql('CREATE INDEX idx_car_parent_status ON child_approval_request (parent_account_id, status)');
        $this->addSql('CREATE INDEX idx_car_child ON child_approval_request (child_player_id)');

        // --- player_trainer_membership: BR-01-27 tracking + AC-01-24 soft removal
        $this->addSql('ALTER TABLE player_trainer_membership ADD COLUMN share_link_id BIGINT DEFAULT NULL');
        $this->addSql('ALTER TABLE player_trainer_membership ADD COLUMN removed_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL');
        $this->addSql(<<<'SQL'
            ALTER TABLE player_trainer_membership
                ADD CONSTRAINT fk_ptm_share_link FOREIGN KEY (share_link_id)
                    REFERENCES share_link (id) ON DELETE RESTRICT
            SQL);
        $this->addSql('CREATE INDEX idx_ptm_share_link ON player_trainer_membership (share_link_id)');

        $this->applyRowLevelSecurity();
    }

    /**
     * Tenancy layer 5. Identical shape to Version20260809140000's — see that
     * migration for the reasoning behind USING + WITH CHECK.
     */
    private function applyRowLevelSecurity(): void
    {
        foreach (self::TRAINER_SCOPED_TABLES as $table) {
            $this->addSql(sprintf('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', $table));

            $this->addSql(sprintf(
                <<<'SQL'
                    CREATE POLICY %1$s_tenant_isolation ON %1$s
                        USING (trainer_id = NULLIF(current_setting('app.current_trainer', true), '')::bigint)
                        WITH CHECK (trainer_id = NULLIF(current_setting('app.current_trainer', true), '')::bigint)
                    SQL,
                $table,
            ));
        }
    }

    public function down(Schema $schema): void
    {
        foreach (self::TRAINER_SCOPED_TABLES as $table) {
            $this->addSql(sprintf('DROP POLICY IF EXISTS %1$s_tenant_isolation ON %1$s', $table));
        }

        $this->addSql('ALTER TABLE player_trainer_membership DROP CONSTRAINT IF EXISTS fk_ptm_share_link');
        $this->addSql('DROP INDEX IF EXISTS idx_ptm_share_link');
        $this->addSql('ALTER TABLE player_trainer_membership DROP COLUMN IF EXISTS removed_at');
        $this->addSql('ALTER TABLE player_trainer_membership DROP COLUMN IF EXISTS share_link_id');

        $this->addSql('DROP TABLE IF EXISTS child_approval_request');
        $this->addSql('DROP TABLE IF EXISTS availability_window');
        $this->addSql('DROP TABLE IF EXISTS coach_membership');
        $this->addSql('DROP TABLE IF EXISTS share_link_open');
        $this->addSql('DROP TABLE IF EXISTS share_link');
        $this->addSql('DROP TABLE IF EXISTS impersonation_session');
        $this->addSql('GRANT UPDATE, DELETE ON audit_log_entry TO pp_app');
        $this->addSql('DROP TABLE IF EXISTS audit_log_entry');
        $this->addSql('DROP TABLE IF EXISTS trainer_branding_settings');
        $this->addSql('DROP TABLE IF EXISTS user_deletion_record');
        $this->addSql('DROP TABLE IF EXISTS password_reset_token');
        $this->addSql('DROP TABLE IF EXISTS email_verification_token');
        $this->addSql('DROP TABLE IF EXISTS parent_child_link');

        $this->addSql('ALTER TABLE player_profile DROP COLUMN IF EXISTS photo_url');
        $this->addSql('ALTER TABLE player_profile DROP COLUMN IF EXISTS emergency_contact_phone');
        $this->addSql('ALTER TABLE player_profile DROP COLUMN IF EXISTS emergency_contact_name');
        $this->addSql('ALTER TABLE player_profile DROP COLUMN IF EXISTS jersey_number');
        $this->addSql('ALTER TABLE player_profile DROP COLUMN IF EXISTS school_or_team');

        $this->addSql('ALTER TABLE trainer DROP COLUMN IF EXISTS organization_description');
        $this->addSql('ALTER TABLE trainer DROP COLUMN IF EXISTS organization_website');
        $this->addSql('ALTER TABLE trainer DROP COLUMN IF EXISTS organization_address');
    }
}
