<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * M6 — Administration (Epic-07): `feature_toggle`, the one table this epic
 * adds. `audit_log_entry`, `impersonation_session` and `platform_subscription`
 * were already created in earlier migrations (M1/M4 respectively) — see
 * their own entity docblocks for exactly which migration and why.
 *
 * **Global, no RLS** — `trainer_id` here is a reference, not a tenancy key
 * (database-designer-schema.md "`feature_toggle`": "this table carries no
 * RLS policy"). Not listed in config/tenancy/trainer_scoped_tables.txt for
 * that reason, matching `platform_subscription`/`stripe_customer_link`'s own
 * precedent in Version20260811100000.
 *
 * **Module placement**: created under this migration's own umbrella
 * (Administration/Epic-07) even though the entity itself lives in
 * `App\Platform\Entity\FeatureToggle` — see that class's own docblock for
 * the forced deviation from the schema doc's literal "Administration"
 * module tag, and why `Platform` is where it has to live for
 * `FeatureGate` to be reachable from `Content`'s and `Growth`'s own voters.
 *
 * **Backfill**: every trainer that already exists at migration time gets
 * all three rows, enabled — BR-07-2's "All three features default to
 * enabled for new trainers" restated for trainers that predate this table.
 * `ON CONFLICT DO NOTHING` makes this safe to run against a database that
 * already has some rows (there are none yet in any environment this
 * migration has actually run against, but the guard costs nothing and
 * matches this codebase's own idempotency conventions elsewhere).
 * `updated_by_account_id` is NOT NULL, so the backfill attributes each
 * trainer's own three rows to that trainer's own owner account — there is
 * no genuine human actor behind a migration-time backfill, and the
 * trainer's own account is the only always-valid, always-present reference
 * available at this point (no cross-table Super Admin lookup needed).
 * `FeatureGate::isEnabled()` also defaults to `true` for any row this
 * backfill somehow misses, as a second, independent line of defense.
 *
 * RLS session variable: `app.current_trainer`, matching every migration
 * since Epic-01 (`App\Platform\Tenancy\TenantContext::SESSION_VARIABLE`) —
 * moot here since this table carries no policy, noted only for consistency
 * with every other migration's own docblock.
 *
 * @see specs/database-designer-schema.md "`feature_toggle` — Administration"
 * @see specs/architect-architecture.md "Entity population — Global"
 * @see specs/requirements-analyst-epic-07-super-admin-spec.md BR-07-1..3, AC-07-18..21
 */
final class Version20260811140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Epic-07: feature_toggle (global, no RLS) + backfill for existing trainers.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform,
            'PracticePerfect targets PostgreSQL only: Row-Level Security is load-bearing.',
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE feature_toggle (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trainer_id BIGINT NOT NULL,
                feature_name VARCHAR(16) NOT NULL,
                is_enabled BOOLEAN DEFAULT true NOT NULL,
                updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                updated_by_account_id BIGINT NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_feature_toggle_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT fk_feature_toggle_updated_by FOREIGN KEY (updated_by_account_id)
                    REFERENCES account (id) ON DELETE RESTRICT,
                CONSTRAINT uniq_feature_toggle_trainer_feature UNIQUE (trainer_id, feature_name),
                CONSTRAINT chk_feature_toggle_name CHECK (feature_name IN ('lppp', 'marketing', 'camps'))
            )
            SQL);
        $this->addSql('CREATE INDEX idx_feature_toggle_trainer ON feature_toggle (trainer_id)');

        // Backfill: every trainer already registered gets all three rows,
        // enabled — see this migration's own docblock.
        $this->addSql(<<<'SQL'
            INSERT INTO feature_toggle (trainer_id, feature_name, is_enabled, updated_at, updated_by_account_id)
            SELECT t.id, f.feature_name, true, now(), t.owner_account_id
            FROM trainer t
            CROSS JOIN (VALUES ('lppp'), ('marketing'), ('camps')) AS f(feature_name)
            ON CONFLICT (trainer_id, feature_name) DO NOTHING
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS feature_toggle');
    }
}
