<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Epic-06: `platform_configuration` — the generic key/JSONB-value singleton
 * settings table `specs/database-designer-schema.md` places in the Platform
 * module (global, no tenant, no RLS). Not built in Epics 01-05 despite the
 * schema doc listing it under the foundational M1 milestone — a genuine gap
 * between that plan and what shipped, recorded here and in the coder's final
 * report rather than silently backfilled with unrelated epics' settings.
 *
 * This migration creates the table and seeds only the three keys Epic-06
 * needs: the referral reward ratio (Q-06.11 default 1:1), the attribution
 * window (Q-06.12 default 30 days), and the referee-welcome-token toggle
 * (Q-06.11 default off). The schema doc also names
 * `default_platform_fee_basis_points`/
 * `default_platform_subscription_price_minor_units`/`token_package_seed` as
 * eventual keys of this same table for Epic-05/07 — deliberately NOT seeded
 * here, since Epic-06 does not need them and inventing values for a
 * different epic's already-settled behavior is out of scope for this
 * change; `PlatformConfigurationRepository::getOrCreate()` provisions any
 * future key lazily on first read regardless.
 *
 * No RLS: global configuration, protected by `PlatformConfigurationVoter`
 * (ROLE_SUPER_ADMIN only), not by tenancy.
 *
 * Runs as the owner role (see the `migrate` make target).
 *
 * @see specs/database-designer-schema.md "`platform_configuration` — Platform"
 * @see specs/requirements-analyst-epic-06-marketing-growth-spec.md AC-06-29..31
 */
final class Version20260811120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Epic-06: platform_configuration (global), seeded with the referral rule defaults.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE platform_configuration (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                config_key VARCHAR(100) NOT NULL,
                value JSON NOT NULL,
                updated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT now() NOT NULL,
                updated_by_account_id BIGINT DEFAULT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_platform_configuration_updated_by FOREIGN KEY (updated_by_account_id)
                    REFERENCES account (id) ON DELETE RESTRICT
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_platform_configuration_key ON platform_configuration (config_key)');

        // Q-06.11/Q-06.12 defaults, seeded at the application/data level
        // (per specs/database-designer-schema.md's own "Seeded rows
        // (application-level, not schema...)" framing) — inserted here
        // rather than left to lazy on-read provisioning so the Super Admin
        // rule screen has a real, auditable starting value from the moment
        // this migration runs, not only after the first visitor happens to
        // trigger a get-or-create.
        $this->addSql(<<<'SQL'
            INSERT INTO platform_configuration (config_key, value, updated_at) VALUES
                ('referral_reward_ratio', '{"referrals": 1, "tokens": 1}', now()),
                ('referral_attribution_window_days', '30', now()),
                ('referee_welcome_token', 'false', now())
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS platform_configuration');
    }
}
