<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Epic-01 foundation: accounts, the tenant registry, the resolver's two global
 * tables, and the first trainer-scoped table with its Row-Level Security
 * policy.
 *
 * Runs as the owner role (see the `migrate` make target). The application role
 * holds no DDL, which is what keeps RLS meaningful.
 *
 * @see specs/database-designer-schema.md
 * @see specs/architect-architecture.md "Tenancy enforcement"
 */
final class Version20260809140000 extends AbstractMigration
{
    /**
     * Tables the tenant resolver reads before a tenant exists. These must
     * never get a policy — mirrored in config/tenancy/resolver_global_tables.txt
     * and asserted by the container startup gate.
     */
    private const RESOLVER_GLOBAL_TABLES = ['account_trainer_link', 'public_tenant_code'];

    /**
     * Trainer-scoped tables created here. Every one must appear in
     * config/tenancy/trainer_scoped_tables.txt.
     */
    private const TRAINER_SCOPED_TABLES = ['player_trainer_membership'];

    public function getDescription(): string
    {
        return 'Epic-01: accounts, trainers, tenant resolution sources, and the first RLS-protected table';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform,
            'PracticePerfect targets PostgreSQL only: Row-Level Security is load-bearing.',
        );

        // Case-insensitive email uniqueness (BR-01-2) without every call site
        // remembering to lowercase.
        $this->addSql('CREATE EXTENSION IF NOT EXISTS citext');

        // --- Global: identity -------------------------------------------------
        $this->addSql(<<<'SQL'
            CREATE TABLE account (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                email CITEXT NOT NULL,
                password_hash VARCHAR(255) NOT NULL,
                role VARCHAR(16) NOT NULL,
                status VARCHAR(16) DEFAULT 'active' NOT NULL,
                email_verified_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                last_login_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT chk_account_role CHECK (role IN ('super_admin','trainer','coach','player')),
                CONSTRAINT chk_account_status CHECK (status IN ('active','inactive','deleted')),
                -- The email is the security identifier. An empty one would
                -- give the firewall a user identifier it cannot authenticate.
                CONSTRAINT chk_account_email_not_empty CHECK (email <> '')
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_account_email ON account (email)');
        $this->addSql('CREATE INDEX idx_account_role ON account (role)');
        $this->addSql('CREATE INDEX idx_account_status ON account (status)');

        $this->addSql(<<<'SQL'
            CREATE TABLE account_profile (
                account_id BIGINT NOT NULL,
                first_name VARCHAR(100) NOT NULL,
                last_name VARCHAR(100) NOT NULL,
                phone VARCHAR(32) DEFAULT NULL,
                photo_url VARCHAR(2048) DEFAULT NULL,
                school_or_organization VARCHAR(255) DEFAULT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY(account_id),
                CONSTRAINT fk_account_profile_account FOREIGN KEY (account_id)
                    REFERENCES account (id) ON DELETE CASCADE
            )
            SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE player_profile (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                self_account_id BIGINT DEFAULT NULL,
                first_name VARCHAR(100) NOT NULL,
                date_of_birth DATE NOT NULL,
                gender VARCHAR(32) DEFAULT NULL,
                is_child BOOLEAN DEFAULT FALSE NOT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_player_profile_self_account FOREIGN KEY (self_account_id)
                    REFERENCES account (id) ON DELETE RESTRICT
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_player_self_account ON player_profile (self_account_id)');

        // --- Global: the tenant registry --------------------------------------
        $this->addSql(<<<'SQL'
            CREATE TABLE trainer (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                owner_account_id BIGINT NOT NULL,
                business_name VARCHAR(255) NOT NULL,
                slug VARCHAR(100) NOT NULL,
                timezone VARCHAR(64) DEFAULT 'America/New_York' NOT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_trainer_owner FOREIGN KEY (owner_account_id)
                    REFERENCES account (id) ON DELETE RESTRICT
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_trainer_owner ON trainer (owner_account_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_trainer_slug ON trainer (slug)');

        // --- Global: the resolver's own sources -------------------------------
        // Read before a tenant exists. RLS here would make every login and
        // every public route silently resolve nothing.
        $this->addSql(<<<'SQL'
            CREATE TABLE account_trainer_link (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                account_id BIGINT NOT NULL,
                trainer_id BIGINT NOT NULL,
                role_in_tenant VARCHAR(16) NOT NULL,
                status VARCHAR(16) DEFAULT 'active' NOT NULL,
                linked_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_atl_account FOREIGN KEY (account_id)
                    REFERENCES account (id) ON DELETE RESTRICT,
                CONSTRAINT fk_atl_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT chk_atl_role CHECK (role_in_tenant IN ('trainer','coach','player')),
                CONSTRAINT chk_atl_status CHECK (status IN ('active','inactive'))
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_account_trainer ON account_trainer_link (account_id, trainer_id)');
        $this->addSql('CREATE INDEX idx_atl_account ON account_trainer_link (account_id)');
        $this->addSql('CREATE INDEX idx_atl_trainer ON account_trainer_link (trainer_id)');

        $this->addSql(<<<'SQL'
            CREATE TABLE public_tenant_code (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                code VARCHAR(64) NOT NULL,
                trainer_id BIGINT NOT NULL,
                kind VARCHAR(16) NOT NULL,
                reference_id BIGINT NOT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_ptc_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT chk_ptc_kind CHECK (kind IN ('sharelink','form'))
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_public_tenant_code ON public_tenant_code (code)');
        $this->addSql('CREATE INDEX idx_ptc_reference ON public_tenant_code (kind, reference_id)');

        // --- Trainer-scoped ----------------------------------------------------
        $this->addSql(<<<'SQL'
            CREATE TABLE player_trainer_membership (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trainer_id BIGINT NOT NULL,
                player_profile_id BIGINT NOT NULL,
                source VARCHAR(32) NOT NULL,
                status VARCHAR(16) DEFAULT 'active' NOT NULL,
                skill_level VARCHAR(50) DEFAULT NULL,
                joined_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_ptm_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT fk_ptm_player FOREIGN KEY (player_profile_id)
                    REFERENCES player_profile (id) ON DELETE RESTRICT,
                CONSTRAINT chk_ptm_source CHECK (source IN ('sharelink','event_registration','coach_invite','camp_registration')),
                CONSTRAINT chk_ptm_status CHECK (status IN ('active','inactive'))
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_player_trainer ON player_trainer_membership (player_profile_id, trainer_id)');
        $this->addSql('CREATE INDEX idx_ptm_trainer ON player_trainer_membership (trainer_id)');

        $this->applyRowLevelSecurity();
    }

    /**
     * Tenancy layer 5.
     *
     * The policy is a plain column comparison against a session variable — no
     * join, no subquery — which is why the tenant key is denormalized onto
     * every trainer-scoped table in the first place.
     *
     * USING governs what is visible; WITH CHECK governs what may be written.
     * Both are needed: without WITH CHECK a caller could insert a row into
     * another trainer's tenant and simply never be able to read it back.
     */
    private function applyRowLevelSecurity(): void
    {
        foreach (self::TRAINER_SCOPED_TABLES as $table) {
            $this->addSql(sprintf('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', $table));

            $this->addSql(sprintf(
                <<<'SQL'
                    CREATE POLICY %1$s_tenant_isolation ON %1$s
                        USING (trainer_id = NULLIF(current_setting('app.current_trainer', true), '')::bigint)
                        WITH CHECK (trainer_id = NULLIF(current_setting('app.current_trainer', true), '')::bigint)
                    SQL,
                $table,
            ));
        }

        // Belt and braces on the resolver's own tables: assert here, at the
        // point of creation, what the startup gate asserts at boot. A future
        // migration that enables RLS on either would break every login.
        foreach (self::RESOLVER_GLOBAL_TABLES as $table) {
            $this->addSql(sprintf(
                <<<'SQL'
                    DO $$
                    BEGIN
                        IF (SELECT relrowsecurity FROM pg_class WHERE oid = '%s'::regclass) THEN
                            RAISE EXCEPTION 'Row-Level Security must never be enabled on %s: the tenant resolver reads it before a tenant exists.';
                        END IF;
                    END $$
                    SQL,
                $table,
                $table,
            ));
        }
    }

    public function down(Schema $schema): void
    {
        foreach (self::TRAINER_SCOPED_TABLES as $table) {
            $this->addSql(sprintf('DROP POLICY IF EXISTS %1$s_tenant_isolation ON %1$s', $table));
        }

        $this->addSql('DROP TABLE IF EXISTS player_trainer_membership');
        $this->addSql('DROP TABLE IF EXISTS public_tenant_code');
        $this->addSql('DROP TABLE IF EXISTS account_trainer_link');
        $this->addSql('DROP TABLE IF EXISTS trainer');
        $this->addSql('DROP TABLE IF EXISTS player_profile');
        $this->addSql('DROP TABLE IF EXISTS account_profile');
        $this->addSql('DROP TABLE IF EXISTS account');
    }
}
