<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * M3a — Crm (Epic-03): labels, player-label associations, system-defined
 * flags, and notes (general, per-event, and coach session feedback — the
 * epic's own text never distinguishes "session" from "event" as attendance
 * units, so both AC-03-20's per-event trainer notes and AC-03-46..49's coach
 * session feedback are the SAME `player_note` row shape, `note_type =
 * 'session'`, distinguished only by who authored it — see PlayerNote's own
 * docblock).
 *
 * Runs as the owner role (see the `migrate` make target).
 *
 * `player_note.event_id` references `event(id)`, which already exists as of
 * Epic-02's migration (Version20260810120000) — no deferred FK needed here.
 *
 * RLS session variable: `app.current_trainer`, matching
 * App\Platform\Tenancy\TenantContext::SESSION_VARIABLE and every migration
 * since Epic-01 — NOT `app.current_trainer_id`, which is what
 * specs/database-designer-schema.md's own "Row-Level Security" section
 * literally shows (a pre-existing documentation/implementation naming
 * mismatch, see Version20260810120000's own docblock).
 *
 * `label.color_hex` uses `VARCHAR(7)`, not the schema doc's literal
 * `CHAR(7)` — Doctrine's `string` DBAL type always schema-diffs to VARCHAR,
 * and no other table in this codebase uses fixed-length CHAR anywhere,
 * so VARCHAR keeps this migration in sync with `doctrine:schema:validate`
 * (see `Label` entity's own mapping) at no behavioral cost for a fixed
 * 7-character value. Same class of small, intentional schema-doc deviation
 * as `app.current_trainer` (not `_trainer_id`) and `share_link_open.ip_address`
 * as VARCHAR (not INET), both already noted by earlier migrations.
 *
 * @see specs/database-designer-schema.md "Crm module (Epic-03)"
 * @see specs/requirements-analyst-epic-03-crm-players-spec.md
 */
final class Version20260810180000 extends AbstractMigration
{
    /**
     * Trainer-scoped tables created here. Every one must appear in
     * config/tenancy/trainer_scoped_tables.txt (already pre-populated).
     */
    private const TRAINER_SCOPED_TABLES = [
        'label',
        'player_label',
        'player_flag',
        'player_note',
    ];

    public function getDescription(): string
    {
        return 'Epic-03: labels, player-label associations, player flags, player notes';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform,
            'PracticePerfect targets PostgreSQL only: Row-Level Security is load-bearing.',
        );

        // --- label -----------------------------------------------------------
        $this->addSql(<<<'SQL'
            CREATE TABLE label (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trainer_id BIGINT NOT NULL,
                name VARCHAR(50) NOT NULL,
                name_normalized VARCHAR(50) GENERATED ALWAYS AS (lower(name)) STORED,
                color_hex VARCHAR(7) NOT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_label_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT chk_label_color CHECK (color_hex ~ '^#[0-9A-Fa-f]{6}$')
            )
            SQL);
        // BR-03-3: case-insensitive uniqueness within one trainer ("Elite" and
        // "elite" collide); two different trainers' "Elite" labels do not
        // (BR-03-4) — trainer_id is the leading column.
        $this->addSql('CREATE UNIQUE INDEX uniq_label_trainer_name_normalized ON label (trainer_id, name_normalized)');

        // --- player_label ------------------------------------------------------
        $this->addSql(<<<'SQL'
            CREATE TABLE player_label (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trainer_id BIGINT NOT NULL,
                player_id BIGINT NOT NULL,
                label_id BIGINT NOT NULL,
                applied_by_account_id BIGINT NOT NULL,
                applied_at TIMESTAMP(0) WITH TIME ZONE DEFAULT now() NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_player_label_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT fk_player_label_player FOREIGN KEY (player_id)
                    REFERENCES player_profile (id) ON DELETE RESTRICT,
                CONSTRAINT fk_player_label_label FOREIGN KEY (label_id)
                    REFERENCES label (id) ON DELETE CASCADE,
                CONSTRAINT fk_player_label_account FOREIGN KEY (applied_by_account_id)
                    REFERENCES account (id) ON DELETE RESTRICT
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_player_label_player_label ON player_label (player_id, label_id)');
        $this->addSql('CREATE INDEX idx_player_label_trainer_label ON player_label (trainer_id, label_id)');

        // --- player_flag ---------------------------------------------------
        $this->addSql(<<<'SQL'
            CREATE TABLE player_flag (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trainer_id BIGINT NOT NULL,
                player_id BIGINT NOT NULL,
                flag_type VARCHAR(24) NOT NULL,
                applied_by_account_id BIGINT NOT NULL,
                applied_at TIMESTAMP(0) WITH TIME ZONE DEFAULT now() NOT NULL,
                note TEXT DEFAULT NULL,
                status VARCHAR(16) DEFAULT 'active' NOT NULL,
                resolved_by_account_id BIGINT DEFAULT NULL,
                resolved_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_player_flag_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT fk_player_flag_player FOREIGN KEY (player_id)
                    REFERENCES player_profile (id) ON DELETE RESTRICT,
                CONSTRAINT fk_player_flag_applied_by FOREIGN KEY (applied_by_account_id)
                    REFERENCES account (id) ON DELETE RESTRICT,
                CONSTRAINT fk_player_flag_resolved_by FOREIGN KEY (resolved_by_account_id)
                    REFERENCES account (id) ON DELETE RESTRICT,
                CONSTRAINT chk_player_flag_type CHECK (flag_type IN (
                    'behavior','high_no_show_rate','injured','medical_restriction',
                    'scholarship','financial_aid','contact_priority','attendance_risk'
                )),
                CONSTRAINT chk_player_flag_status CHECK (status IN ('active','resolved')),
                CONSTRAINT chk_player_flag_resolved_shape CHECK (
                    (status = 'resolved') = (resolved_at IS NOT NULL AND resolved_by_account_id IS NOT NULL)
                )
            )
            SQL);
        // BR-03-8: at most one ACTIVE instance of a given flag per player,
        // while still allowing reapplication after resolution (a second row).
        $this->addSql("CREATE UNIQUE INDEX uniq_player_flag_active_type ON player_flag (player_id, flag_type) WHERE status = 'active'");
        $this->addSql("CREATE INDEX idx_player_flag_trainer_type_active ON player_flag (trainer_id, flag_type) WHERE status = 'active'");

        // --- player_note -----------------------------------------------------
        $this->addSql(<<<'SQL'
            CREATE TABLE player_note (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                trainer_id BIGINT NOT NULL,
                player_id BIGINT NOT NULL,
                note_type VARCHAR(16) NOT NULL,
                event_id BIGINT DEFAULT NULL,
                note_text VARCHAR(1000) NOT NULL,
                created_by_account_id BIGINT NOT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                edited_by_account_id BIGINT DEFAULT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_player_note_trainer FOREIGN KEY (trainer_id)
                    REFERENCES trainer (id) ON DELETE RESTRICT,
                CONSTRAINT fk_player_note_player FOREIGN KEY (player_id)
                    REFERENCES player_profile (id) ON DELETE RESTRICT,
                CONSTRAINT fk_player_note_event FOREIGN KEY (event_id)
                    REFERENCES event (id) ON DELETE RESTRICT,
                CONSTRAINT fk_player_note_created_by FOREIGN KEY (created_by_account_id)
                    REFERENCES account (id) ON DELETE RESTRICT,
                CONSTRAINT fk_player_note_edited_by FOREIGN KEY (edited_by_account_id)
                    REFERENCES account (id) ON DELETE RESTRICT,
                CONSTRAINT chk_player_note_type CHECK (note_type IN ('general','session')),
                CONSTRAINT chk_player_note_session_event CHECK (
                    (note_type = 'session') = (event_id IS NOT NULL)
                ),
                CONSTRAINT chk_player_note_text_length CHECK (char_length(note_text) <= 1000)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_player_note_player_created ON player_note (player_id, created_at DESC)');
        $this->addSql('CREATE INDEX idx_player_note_event ON player_note (event_id)');

        $this->applyRowLevelSecurity();
    }

    /**
     * Tenancy layer 5. Identical shape to every migration since Epic-01 — see
     * Version20260810120000 for the reasoning behind USING + WITH CHECK.
     */
    private function applyRowLevelSecurity(): void
    {
        foreach (self::TRAINER_SCOPED_TABLES as $table) {
            $this->addSql(sprintf('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', $table));

            $this->addSql(sprintf(
                <<<'SQL'
                    CREATE POLICY %1$s_tenant_isolation ON %1$s
                        USING (trainer_id = NULLIF(current_setting('app.current_trainer', true), '')::bigint)
                        WITH CHECK (trainer_id = NULLIF(current_setting('app.current_trainer', true), '')::bigint)
                    SQL,
                $table,
            ));
        }
    }

    public function down(Schema $schema): void
    {
        foreach (self::TRAINER_SCOPED_TABLES as $table) {
            $this->addSql(sprintf('DROP POLICY IF EXISTS %1$s_tenant_isolation ON %1$s', $table));
        }

        $this->addSql('DROP TABLE IF EXISTS player_note');
        $this->addSql('DROP TABLE IF EXISTS player_flag');
        $this->addSql('DROP TABLE IF EXISTS player_label');
        $this->addSql('DROP TABLE IF EXISTS label');
    }
}
