#!/usr/bin/env python3
"""Infrastructure ownership and update-safety regressions."""

from __future__ import annotations

import contextlib
import importlib.util
import io
import json
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / ".agents/skills/bootstrap-verifier/scripts"
sys.path.insert(0, str(SCRIPTS))

import infra_ownership as ownership  # noqa: E402

VALIDATOR_PATH = SCRIPTS / "validate_generated.py"
SPEC = importlib.util.spec_from_file_location("validate_generated", VALIDATOR_PATH)
validator = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(validator)

VERSION = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
STAMP = (
    f"<!-- Generated by Infrastructure-Creator v{VERSION} | "
    "TASK-001 | 2026-08-06 -->\n"
)


class OwnershipFixture(unittest.TestCase):
    def setUp(self) -> None:
        self._temporary = tempfile.TemporaryDirectory(prefix="infra-ownership-")
        self.base = Path(self._temporary.name).resolve()
        self.target = self.base / "target with spaces"
        self.staging = self.base / "staging"
        self.target.mkdir()
        self.staging.mkdir()
        self.target = self.target.resolve()
        self.staging = self.staging.resolve()
        self.addCleanup(self._temporary.cleanup)

    def write(self, rel: str, content: str, *, staging: bool = False) -> Path:
        root = self.staging if staging else self.target
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        return path

    def manifest(
        self,
        paths: list[str],
        *,
        mode: str = "full",
        decisions: dict | None = None,
        task: str = "TASK-001",
    ) -> dict:
        manifest = ownership.build_manifest(
            self.target,
            paths,
            generator="Infrastructure-Creator",
            generator_version=VERSION,
            task=task,
            profile=f"tasks/{task}/infra-scan-project-profile.md",
            editions=["claude"],
            mode=mode,
            decisions=decisions,
            generated_at="2026-08-06T08:00:00Z",
        )
        ownership.write_manifest(self.target, manifest)
        return manifest

    def manifest_errors(self) -> list[str]:
        errors: list[str] = []
        validator.validate_manifest(self.target, errors)
        return errors


class ManifestOwnershipTest(OwnershipFixture):
    TEAM_PATHS = (
        ".claude/skills/team-notes/SKILL.md",
        ".cursor/agents/team-agent.md",
        ".agents/skills/team-skill/SKILL.md",
        ".codex/hooks/team-hook.sh",
        "memory-bank/team-notes.md",
        "project-brain/team-notes.md",
    )

    def test_unmanifested_team_placeholders_are_ignored_in_full_and_merge(self) -> None:
        for mode in ("full", "merge"):
            with self.subTest(mode=mode):
                owned = self.write(
                    "AGENTS.md",
                    STAMP + "# Generated policy\nNo placeholders.\n",
                )
                for rel in self.TEAM_PATHS:
                    self.write(rel, "TODO FIXME YYYY-MM-DD\n")
                manifest = self.manifest(["AGENTS.md"], mode=mode)

                errors: list[str] = []
                validator.validate_manifest(self.target, errors)
                validator.validate_owned_placeholders(
                    self.target, manifest["files"], errors
                )

                self.assertEqual(errors, [])
                self.assertTrue(owned.exists())
                for rel in self.TEAM_PATHS:
                    self.assertEqual(
                        (self.target / rel).read_text(encoding="utf-8"),
                        "TODO FIXME YYYY-MM-DD\n",
                    )

    def test_untracked_team_agents_file_is_not_opened_or_stamp_checked(self) -> None:
        self.write("AGENTS.md", "TODO team policy YYYY-MM-DD\n")
        self.write(".claude/generated.md", "generated\n")
        manifest = self.manifest([".claude/generated.md"], mode="merge")
        errors: list[str] = []
        validator.validate_manifest(self.target, errors)
        validator.validate_owned_placeholders(self.target, manifest["files"], errors)
        self.assertEqual(errors, [])

    def test_manifest_owned_placeholder_fails(self) -> None:
        self.write("AGENTS.md", STAMP + "TODO generated placeholder\n")
        manifest = self.manifest(["AGENTS.md"])
        errors: list[str] = []
        validator.validate_manifest(self.target, errors)
        validator.validate_owned_placeholders(self.target, manifest["files"], errors)
        self.assertTrue(any("leftover placeholder" in error for error in errors))

    def test_placeholder_ownership_matrix(self) -> None:
        cases = (
            "{skill-name}",
            "{NNNN}",
            "TODO",
            "FIXME",
            "YYYY-MM-DD",
            "[target_name]",
            "TASK-{N}",
            "{{PROJECT_NAME}}",
        )
        for index, placeholder in enumerate(cases):
            with self.subTest(placeholder=placeholder):
                owned_rel = f"generated/{index}.md"
                team_rel = f"team/{index}.md"
                self.write(owned_rel, placeholder + "\n")
                team = self.write(team_rel, placeholder + "\n")
                manifest = self.manifest([owned_rel])
                errors: list[str] = []
                validator.validate_owned_placeholders(
                    self.target, manifest["files"], errors
                )
                self.assertTrue(any(owned_rel in error for error in errors))
                self.assertFalse(any(team_rel in error for error in errors))
                self.assertEqual(team.read_text(encoding="utf-8"), placeholder + "\n")

    def test_missing_tracked_file_fails(self) -> None:
        path = self.write("AGENTS.md", STAMP + "generated\n")
        self.manifest(["AGENTS.md"])
        path.unlink()
        self.assertTrue(any("tracked file missing" in error for error in self.manifest_errors()))

    def test_hash_drift_fails(self) -> None:
        path = self.write("AGENTS.md", STAMP + "generated\n")
        self.manifest(["AGENTS.md"])
        path.write_text(STAMP + "team edit\n", encoding="utf-8")
        self.assertTrue(any("sha256 mismatch" in error for error in self.manifest_errors()))

    def test_final_symlink_is_never_manifest_owned_or_safe_to_update(self) -> None:
        path = self.write("AGENTS.md", STAMP + "generated\n")
        manifest = self.manifest(["AGENTS.md"])
        outside = self.base / "outside.md"
        outside.write_text(STAMP + "generated\n", encoding="utf-8")
        path.unlink()
        path.symlink_to(outside)
        self.write("AGENTS.md", STAMP + "replacement\n", staging=True)

        with self.assertRaisesRegex(ownership.OwnershipError, "symlink"):
            ownership.classify_update(self.target, self.staging, manifest)
        errors = self.manifest_errors()
        self.assertTrue(any("unsafe tracked path AGENTS.md" in error for error in errors))
        self.assertEqual(STAMP + "generated\n", outside.read_text(encoding="utf-8"))

    def test_symlinked_parent_is_never_manifest_owned_or_safe_to_update(self) -> None:
        path = self.write(".claude/generated.md", "generated\n")
        manifest = self.manifest([".claude/generated.md"])
        outside = self.base / "outside"
        outside.mkdir()
        outside_file = outside / "generated.md"
        outside_file.write_text("generated\n", encoding="utf-8")
        path.unlink()
        path.parent.rmdir()
        path.parent.symlink_to(outside, target_is_directory=True)
        self.write(".claude/generated.md", "replacement\n", staging=True)

        with self.assertRaisesRegex(ownership.OwnershipError, "symlink"):
            ownership.classify_update(self.target, self.staging, manifest)
        errors = self.manifest_errors()
        self.assertTrue(
            any("unsafe tracked path .claude/generated.md" in error for error in errors)
        )
        self.assertEqual("generated\n", outside_file.read_text(encoding="utf-8"))

    def test_symlinked_target_root_is_rejected_before_confinement(self) -> None:
        outside = self.base / "outside-target"
        outside.mkdir()
        linked_target = self.base / "linked-target"
        linked_target.symlink_to(outside, target_is_directory=True)

        with self.assertRaisesRegex(ownership.OwnershipError, "symlink"):
            ownership.resolve_target(linked_target)
        with self.assertRaisesRegex(ownership.OwnershipError, "symlink"):
            ownership.confined_target_path(linked_target, "AGENTS.md")
        self.assertEqual([], list(outside.iterdir()))

    def test_stamp_drift_fails_even_when_hash_matches(self) -> None:
        self.write(
            "AGENTS.md",
            "<!-- Generated by Infrastructure-Creator v0.0.1 | "
            "TASK-999 | 2026-08-06 -->\ngenerated\n",
        )
        self.manifest(["AGENTS.md"])
        errors = self.manifest_errors()
        self.assertTrue(any("stamp version" in error for error in errors))
        self.assertTrue(any("stamp task" in error for error in errors))

    def test_decision_schema_validates_every_documented_field(self) -> None:
        self.write("AGENTS.md", STAMP + "generated\n")
        staged_hash = "a" * 64
        valid = {
            "AGENTS.md": {
                "decision": "kept",
                "rejected_sha256": staged_hash,
                "task": "TASK-002",
            }
        }
        self.manifest(["AGENTS.md"], decisions=valid)
        self.assertEqual(self.manifest_errors(), [])

        invalid_entries = (
            {"decision": "unknown", "rejected_sha256": staged_hash, "task": "TASK-002"},
            {"decision": "kept", "rejected_sha256": "bad", "task": "TASK-002"},
            {"decision": "kept", "rejected_sha256": staged_hash},
            {"decision": "merged", "rejected_sha256": staged_hash, "task": "task-2"},
        )
        for entry in invalid_entries:
            with self.subTest(entry=entry):
                with self.assertRaises(ownership.OwnershipError):
                    self.manifest(
                        ["AGENTS.md"], decisions={"AGENTS.md": entry}
                    )

    def test_structured_decision_schema_is_additive_and_extensible(self) -> None:
        target_file = self.write(".gitignore", "team\n# generated\n.cache/\n")
        proposal = "a" * 64
        structured = {
            ".gitignore": {
                "decision": "merged",
                "rejected_sha256": proposal,
                "task": "TASK-002",
                "origin": "shared",
                "strategy": "append-requirements",
                "proposal_sha256": proposal,
                "resolved_sha256": ownership.sha256_file(target_file),
                "requirements": [".cache/", "memory-bank/local/"],
                "future_metadata": {"schema": 2},
            }
        }
        manifest = self.manifest([".gitignore"], decisions=structured)
        self.assertEqual(self.manifest_errors(), [])
        self.assertEqual(manifest["manifest_version"], 1)
        self.assertEqual(
            manifest["decisions"][".gitignore"]["future_metadata"], {"schema": 2}
        )
        satisfied = {
            ".gitignore": {
                **structured[".gitignore"],
                "decision": "kept",
                "strategy": "keep",
                "rejected_sha256": ownership.sha256_file(target_file),
                "proposal_sha256": ownership.sha256_file(target_file),
            }
        }
        self.manifest([".gitignore"], decisions=satisfied)
        self.assertEqual(self.manifest_errors(), [])

    def test_structured_decision_rejects_partial_and_contradictory_entries(self) -> None:
        target_file = self.write(".gitignore", "team\n")
        resolved = ownership.sha256_file(target_file)
        base = {
            "decision": "merged",
            "rejected_sha256": "a" * 64,
            "task": "TASK-002",
            "origin": "shared",
            "strategy": "append-requirements",
            "proposal_sha256": "a" * 64,
            "resolved_sha256": resolved,
            "requirements": [".cache/"],
        }
        invalid = (
            {key: value for key, value in base.items() if key != "origin"},
            {**base, "decision": "kept"},
            {**base, "origin": "generated"},
            {**base, "proposal_sha256": "b" * 64},
            {**base, "resolved_sha256": "b" * 64},
            {**base, "requirements": [".cache/", ".cache/"]},
            {**base, "requirements": ["memory/", ".cache/"]},
            {**base, "requirements": []},
        )
        for entry in invalid:
            with self.subTest(entry=entry):
                with self.assertRaises(ownership.OwnershipError):
                    self.manifest([".gitignore"], decisions={".gitignore": entry})

    def test_decision_for_untracked_file_fails(self) -> None:
        self.write("AGENTS.md", STAMP + "generated\n")
        with self.assertRaisesRegex(
            ownership.OwnershipError, "outside manifest membership"
        ):
            self.manifest(
                ["AGENTS.md"],
                decisions={
                    "team.md": {
                        "decision": "kept",
                        "rejected_sha256": "a" * 64,
                        "task": "TASK-002",
                    }
                },
            )


class UpdateClassificationTest(OwnershipFixture):
    def test_standing_keep_and_merge_decisions_are_honored(self) -> None:
        for decision in ("kept", "merged"):
            with self.subTest(decision=decision):
                self.write(".claude/hooks/local-context.sh", "team version\n")
                staged = self.write(
                    ".claude/hooks/local-context.sh",
                    "declined generated version\n",
                    staging=True,
                )
                manifest = self.manifest(
                    [".claude/hooks/local-context.sh"],
                    decisions={
                        ".claude/hooks/local-context.sh": {
                            "decision": decision,
                            "rejected_sha256": ownership.sha256_file(staged),
                            "task": "TASK-002",
                        }
                    },
                )
                rows = ownership.classify_update(self.target, self.staging, manifest)
                self.assertEqual(rows[0]["classification"], "standing-decision-honored")
                self.assertEqual(rows[0]["reason"], decision)

    def test_changed_staged_output_reopens_decision(self) -> None:
        self.write(".claude/hooks/local-context.sh", "team version\n")
        self.write(
            ".claude/hooks/local-context.sh", "new generated version\n", staging=True
        )
        manifest = self.manifest(
            [".claude/hooks/local-context.sh"],
            decisions={
                ".claude/hooks/local-context.sh": {
                    "decision": "kept",
                    "rejected_sha256": "a" * 64,
                    "task": "TASK-002",
                }
            },
        )
        rows = ownership.classify_update(self.target, self.staging, manifest)
        self.assertEqual(rows[0]["classification"], "requires-decision")
        self.assertEqual(rows[0]["reason"], "generator-output-changed")

    def test_structured_classification_prefers_proposal_and_strategy(self) -> None:
        target_file = self.write(".gitignore", "team\n.cache/\n")
        staged = self.write(".gitignore", "proposed block\n", staging=True)
        proposal = ownership.sha256_file(staged)
        manifest = self.manifest(
            [".gitignore"],
            decisions={
                ".gitignore": {
                    "decision": "merged",
                    "rejected_sha256": proposal,
                    "task": "TASK-002",
                    "origin": "shared",
                    "strategy": "append-requirements",
                    "proposal_sha256": proposal,
                    "resolved_sha256": ownership.sha256_file(target_file),
                    "requirements": [".cache/"],
                }
            },
        )
        row = ownership.classify_update(self.target, self.staging, manifest)[0]
        self.assertEqual(row["classification"], "standing-decision-honored")
        self.assertEqual(row["reason"], "append-requirements")

    def test_staged_manifest_is_never_a_classify_row(self) -> None:
        self.write("AGENTS.md", STAMP + "generated\n")
        manifest = self.manifest(["AGENTS.md"])
        self.write("AGENTS.md", STAMP + "generated\n", staging=True)
        staged_manifest = ownership.build_manifest(
            self.staging,
            ["AGENTS.md"],
            generator="Infrastructure-Creator",
            generator_version=VERSION,
            task="TASK-002",
            profile="tasks/TASK-002/infra-scan-project-profile.md",
            editions=["claude"],
            mode="full",
            generated_at="2026-08-06T08:00:00Z",
        )
        ownership.write_manifest(self.staging, staged_manifest)

        rows = ownership.classify_update(self.target, self.staging, manifest)

        self.assertEqual([row["path"] for row in rows], ["AGENTS.md"])
        self.assertEqual(rows[0]["classification"], "safe-update")

    def test_malformed_decision_entry_raises_ownership_error(self) -> None:
        self.write("AGENTS.md", STAMP + "generated\n")
        manifest = self.manifest(["AGENTS.md"])
        manifest["decisions"] = {"AGENTS.md": "kept"}
        ownership.write_manifest(self.target, manifest)
        self.write("AGENTS.md", STAMP + "generated\n", staging=True)

        with self.assertRaisesRegex(
            ownership.OwnershipError, "decision entry must be an object"
        ):
            ownership.classify_update(
                self.target, self.staging, ownership.load_manifest(self.target)
            )
        stderr = io.StringIO()
        with contextlib.redirect_stderr(stderr):
            code = ownership.main(
                [
                    "classify",
                    "--target",
                    str(self.target),
                    "--staging",
                    str(self.staging),
                ]
            )
        self.assertEqual(code, 2)
        self.assertIn("ERROR: ", stderr.getvalue())
        self.assertIn("decision entry must be an object", stderr.getvalue())

    def test_malformed_external_decisions_json_fails_cleanly(self) -> None:
        self.write("AGENTS.md", "generated\n", staging=True)
        write_plan = self.base / "write-plan.txt"
        write_plan.write_text("AGENTS.md\n", encoding="utf-8")
        decisions = self.base / "decisions.json"
        decisions.write_text(json.dumps({"AGENTS.md": "kept"}), encoding="utf-8")
        source_map = self.base / "sources.json"
        source_map.write_text(json.dumps({}), encoding="utf-8")

        stderr = io.StringIO()
        with contextlib.redirect_stderr(stderr):
            code = ownership.main(
                [
                    "manifest",
                    "--target",
                    str(self.staging),
                    "--write-plan",
                    str(write_plan),
                    "--version",
                    VERSION,
                    "--task",
                    "TASK-002",
                    "--profile",
                    "tasks/TASK-002/infra-scan-project-profile.md",
                    "--editions",
                    "claude",
                    "--mode",
                    "full",
                    "--source-target",
                    str(self.target),
                    "--source-map",
                    str(source_map),
                    "--decisions",
                    str(decisions),
                ]
            )
        self.assertEqual(code, 2)
        self.assertIn("ERROR: ", stderr.getvalue())
        self.assertIn("decision entry must be an object", stderr.getvalue())

    def test_legacy_target_refuses_without_writes(self) -> None:
        marker = self.write(".claude/team.md", "unchanged\n")
        before = marker.read_bytes()
        with self.assertRaisesRegex(ownership.OwnershipError, "refusing update"):
            ownership.load_manifest(self.target)
        self.assertEqual(marker.read_bytes(), before)
        self.assertFalse((self.target / ownership.MANIFEST_NAME).exists())

    def test_generate_edit_classify_keep_revalidate_lifecycle(self) -> None:
        self.write("AGENTS.md", STAMP + "generated policy\n")
        hook = self.write(".claude/hooks/local-context.sh", "generated v1\n")
        manifest = self.manifest(
            ["AGENTS.md", ".claude/hooks/local-context.sh"], mode="full"
        )
        initial_errors: list[str] = []
        validator.validate_manifest(self.target, initial_errors)
        validator.validate_owned_placeholders(
            self.target, manifest["files"], initial_errors
        )
        self.assertEqual(initial_errors, [])

        hook.write_text("generated v1\n# team edit\n", encoding="utf-8")
        team_file = self.write(".claude/team-notes.md", "TODO team-owned\n")
        next_stamp = (
            f"<!-- Generated by Infrastructure-Creator v{VERSION} | "
            "TASK-002 | 2026-08-06 -->\n"
        )
        staged_agents = self.write(
            "AGENTS.md", next_stamp + "generated policy\n", staging=True
        )
        staged = self.write(
            ".claude/hooks/local-context.sh", "generated v2\n", staging=True
        )
        rows = ownership.classify_update(self.target, self.staging, manifest)
        self.assertEqual(
            rows,
            [
                {
                    "path": ".claude/hooks/local-context.sh",
                    "classification": "requires-decision",
                    "reason": "tracked-file-modified",
                },
                {
                    "path": "AGENTS.md",
                    "classification": "safe-update",
                    "reason": "manifest-hash-unchanged",
                },
            ],
        )
        self.assertNotIn("team-notes.md", str(rows))

        (self.target / "AGENTS.md").write_bytes(staged_agents.read_bytes())
        refreshed = self.manifest(
            ["AGENTS.md", ".claude/hooks/local-context.sh"],
            mode="full",
            decisions={
                ".claude/hooks/local-context.sh": {
                    "decision": "kept",
                    "rejected_sha256": ownership.sha256_file(staged),
                    "task": "TASK-002",
                }
            },
            task="TASK-002",
        )
        final_errors: list[str] = []
        validator.validate_manifest(self.target, final_errors)
        validator.validate_owned_placeholders(
            self.target, refreshed["files"], final_errors
        )
        self.assertEqual(final_errors, [])
        self.assertEqual(team_file.read_text(encoding="utf-8"), "TODO team-owned\n")
        rerun = ownership.classify_update(self.target, self.staging, refreshed)
        by_path = {row["path"]: row for row in rerun}
        self.assertEqual(
            by_path[".claude/hooks/local-context.sh"]["classification"],
            "standing-decision-honored",
        )


class TargetPathSemanticsTest(OwnershipFixture):
    def test_relative_path_is_caller_relative_and_supports_spaces(self) -> None:
        self.assertEqual(
            ownership.resolve_target("target with spaces", self.base), self.target
        )

    def test_absolute_path_is_independent_of_cwd(self) -> None:
        wrong_cwd = self.base / "wrong cwd"
        wrong_cwd.mkdir()
        self.assertEqual(ownership.resolve_target(self.target, wrong_cwd), self.target)

    def test_relative_path_from_wrong_cwd_does_not_retarget_silently(self) -> None:
        wrong_cwd = self.base / "wrong cwd"
        wrong_cwd.mkdir()
        resolved = ownership.resolve_target("target with spaces", wrong_cwd)
        self.assertEqual(resolved, (wrong_cwd / "target with spaces").resolve())
        self.assertNotEqual(resolved, self.target)
        self.assertFalse(resolved.exists())


if __name__ == "__main__":
    unittest.main()
