#!/usr/bin/env python3
"""Regression tests for bootstrap-verifier's validate_generated.py.

Scope: the manifest-as-ownership contract (defects TC-008 / TC-014):

- TC-008: the leftover-placeholder scan applies ONLY to manifest-tracked
  (generator-owned) files. A merge-mode target whose PRE-EXISTING team
  AGENTS.md contains the word TODO must not fail verification - the team's
  files are never scanned.
- TC-014: there is no disk-to-manifest coverage walk in any mode. A file
  the team adds under an edition root after a full generation (their own
  skill in .claude/skills) is untouchable, never a "generated file not
  tracked" error - while every file the manifest DOES list must still
  exist with a matching sha256.

The validator ships in three byte-identical copies; behaviour is exercised
through the .claude copy (as test_hooks.py does for hooks) and the identity
itself is asserted separately.

Run from this directory: python3 -m unittest discover
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
import tempfile
import unittest
from pathlib import Path

EDITION_ROOT = Path(__file__).resolve().parents[1]
SCRIPT_REL = "skills/bootstrap-verifier/scripts/validate_generated.py"
MIRROR_COPIES = (".claude/" + SCRIPT_REL, ".agents/" + SCRIPT_REL, ".cursor/" + SCRIPT_REL)
GENERATOR_VERSION = (EDITION_ROOT / "VERSION").read_text(encoding="utf-8").strip()
TASK = "TASK-9"
STAMP = (
    f"<!-- Generated by Infrastructure-Creator v{GENERATOR_VERSION}"
    f" | {TASK} | 2026-08-03 -->"
)


def load_validator():
    """Import the shipped validator module from the .claude mirror copy."""
    path = EDITION_ROOT / MIRROR_COPIES[0]
    spec = importlib.util.spec_from_file_location("validate_generated_under_test", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


class FakeTargetMixin:
    """A throwaway target root plus manifest-writing helpers."""

    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory(prefix="infra-validate-tests-")
        self.target = Path(self._tmp.name) / "target"
        self.target.mkdir()
        self.addCleanup(self._tmp.cleanup)
        self.mod = load_validator()

    def write(self, rel: str, text: str) -> Path:
        path = self.target / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        return path

    def write_manifest(self, tracked_rels, mode: str) -> Path:
        manifest = {
            "manifest_version": 1,
            "generator": "Infrastructure-Creator",
            "generator_version": GENERATOR_VERSION,
            "task": TASK,
            "profile": f"tasks/{TASK}/infra-scan-project-profile.md",
            "generated_at": "2026-08-03T00:00:00Z",
            "editions": ["claude"],
            "mode": mode,
            "files": {rel: sha256(self.target / rel) for rel in tracked_rels},
        }
        return self.write(
            ".infra-manifest.json", json.dumps(manifest, indent=2) + "\n"
        )


class PlaceholderOwnershipTest(FakeTargetMixin, unittest.TestCase):
    """TC-008: placeholders are a defect only in generator-owned files."""

    def setUp(self) -> None:
        super().setUp()
        # The team's pre-existing surface from the TC-008 repro: a root
        # AGENTS.md and a custom hook, both containing the word TODO, both
        # untracked (merge mode never claims pre-existing files).
        self.team_agents = self.write(
            "AGENTS.md", "# Team agents guide\n\nTODO: onboard the new service.\n"
        )
        self.team_hook = self.write(
            ".claude/hooks/deploy-check.sh", "#!/bin/bash\n# TODO tighten\nexit 0\n"
        )
        # One generator-owned file, clean, tracked.
        self.generated = self.write(
            ".claude/skills/coder/SKILL.md",
            "---\nname: coder\ndescription: x\n---\n\n# Coder\n",
        )
        self.write_manifest([".claude/skills/coder/SKILL.md"], mode="merge")
        self.tracked = self.mod.load_tracked_files(self.target)

    def test_tracked_set_reflects_manifest_files_only(self) -> None:
        self.assertEqual(self.tracked, {".claude/skills/coder/SKILL.md"})

    def test_team_files_with_todo_are_never_scanned(self) -> None:
        errors: list = []
        for team_file in (self.team_agents, self.team_hook):
            self.mod.check_placeholders(team_file, errors, self.target, self.tracked)
        self.assertEqual(errors, [])

    def test_generator_owned_file_with_todo_still_fails(self) -> None:
        self.generated.write_text(
            "---\nname: coder\ndescription: x\n---\n\nTODO finish\n",
            encoding="utf-8",
        )
        errors: list = []
        self.mod.check_placeholders(self.generated, errors, self.target, self.tracked)
        self.assertEqual(len(errors), 1)
        self.assertIn("leftover placeholder", errors[0])

    def test_without_a_readable_manifest_every_candidate_is_scanned(self) -> None:
        # Fallback: no manifest -> no ownership info -> legacy behaviour
        # (validate_manifest reports the missing manifest itself).
        (self.target / ".infra-manifest.json").unlink()
        self.assertIsNone(self.mod.load_tracked_files(self.target))
        errors: list = []
        self.mod.check_placeholders(self.team_agents, errors, self.target, None)
        self.assertEqual(len(errors), 1)


class ManifestCoverageTest(FakeTargetMixin, unittest.TestCase):
    """TC-014: files outside the manifest are untouchable, not errors."""

    GENERATED = (
        "AGENTS.md",
        ".claude/skills/coder/SKILL.md",
        ".claude/hooks/local-context.sh",
    )

    def setUp(self) -> None:
        super().setUp()
        self.write("AGENTS.md", STAMP + "\n\n# Agents\n")
        self.write(
            ".claude/skills/coder/SKILL.md",
            "---\nname: coder\ndescription: x\n---\n\n# Coder\n",
        )
        self.write(".claude/hooks/local-context.sh", "#!/bin/bash\nexit 0\n")
        self.write_manifest(self.GENERATED, mode="full")

    def validate(self) -> list:
        errors: list = []
        self.mod.validate_manifest(self.target, errors)
        return errors

    def test_clean_full_mode_manifest_passes(self) -> None:
        self.assertEqual(self.validate(), [])

    def test_team_added_files_under_edition_roots_are_not_errors(self) -> None:
        # The TC-014 repro surface: an unmanifested team note under .claude
        # plus the team's own skill in .claude/skills, after a full-mode
        # generation. Both are untouchable - never "generated file not
        # tracked" noise that would clinch a later infra-update run.
        self.write(".claude/skills-notes.md", "# our notes\n")
        self.write(
            ".claude/skills/team-own/SKILL.md",
            "---\nname: team-own\ndescription: ours\n---\n\n# Ours\n",
        )
        self.assertEqual(self.validate(), [])

    def test_tracked_file_missing_from_target_still_fails(self) -> None:
        (self.target / ".claude/hooks/local-context.sh").unlink()
        errors = self.validate()
        self.assertEqual(len(errors), 1)
        self.assertIn("tracked file missing from target", errors[0])

    def test_tracked_file_hash_mismatch_still_fails(self) -> None:
        self.write(".claude/hooks/local-context.sh", "#!/bin/bash\nexit 1\n")
        errors = self.validate()
        self.assertEqual(len(errors), 1)
        self.assertIn("sha256 mismatch", errors[0])


class MirrorConsistencyTest(unittest.TestCase):
    def test_validator_byte_identical_across_mirrors(self) -> None:
        # Documented invariant: skills (bundled scripts included) ship
        # byte-identical in the .agents/.claude/.cursor mirrors.
        reference = (EDITION_ROOT / MIRROR_COPIES[0]).read_bytes()
        for mirror in MIRROR_COPIES[1:]:
            with self.subTest(mirror=mirror):
                self.assertEqual(reference, (EDITION_ROOT / mirror).read_bytes())


if __name__ == "__main__":
    unittest.main()
